[postgresql]
; host=localhost
; database=postgres
; user=postgres
; password=subbu
; port=5433

host=prathampostgresql.postgres.database.azure.com
database=graviton
user=decdpdev
password=postgres@2022
port=5432
