# Generated by Django 3.2.12 on 2022-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0006_alter_rule_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_name', models.CharField(max_length=100)),
                ('dataset_name', models.CharField(max_length=100)),
                ('expectation_suite_name', models.CharField(max_length=100)),
                ('run_name', models.CharField(max_length=100)),
                ('expectation_name', models.CharField(max_length=100)),
                ('dq_dimension', models.CharField(max_length=100)),
                ('result_status', models.BooleanField()),
                ('result_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
