# Generated by Django 3.2.12 on 2022-03-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0007_resultv1'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultv1',
            name='expectation_config',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resultv1',
            name='result_json',
            field=models.TextField(default=''),
        ),
    ]
