# Generated by Django 3.2.12 on 2022-03-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0008_auto_20220308_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultv1',
            name='cde_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
