[postgresql]
host=prathampostgresql.postgres.database.azure.com
database=marshal
user=decdpdev
password=postgres@2022
port=5432

; host=localhost
; user=postgres
; password=mypostpass123
; port=5432
; database=DQC_DB