# Generated by Django 2.2.10 on 2021-11-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdvmodel',
            name='sdv_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sdvmodel',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
