package com.naturetools.app.model

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector

enum class BadgeType { NONE, NEW, PREMIUM }

data class Tool(
    val name: String,
    val icon: ImageVector,
    val route: String,
    val category: String,
    val color: Color = Color.Unspecified,
    val badge: BadgeType = BadgeType.NONE,
    val description: String? = null,
    val isVisibleOnHome: Boolean = true,
    val subToolRoutes: List<String>? = null,
    val isSubTool: Boolean = false
)

object ToolProvider {
    val tools = listOf(
        // Smart Utilities
        Tool("AI Expert", Icons.Default.AutoAwesome, "ai_group", "Smart Utilities", Color(0xFF673AB7),
            description = "AI-powered tools for chat, image generation, audio processing and more.",
            subToolRoutes = listOf("ai_chat", "ai_summarizer", "ai_image", "ai_code", "ai_grammar", "ai_obj_detect", "ai_sentiment", "ai_text_ext", "ai_translate", "ai_noise_remover", "ai_voice_mimic", "ai_stems_splitter", "audio_noise_remover", "echo_remover", "reverb_remover", "video_noise_remover", "vocal_autotuner", "vocal_remover", "image_ai_tools")),
        Tool("Audio Noise Remover", Icons.Default.MicOff, "audio_noise_remover", "Smart Utilities", Color(0xFF2196F3), isVisibleOnHome = false, isSubTool = true, description = "Remove unwanted noise from your audio recordings."),
        Tool("CSV to JSON", Icons.Default.Transform, "csv_to_json", "Smart Utilities", Color(0xFF009688),  description = "Convert CSV data to JSON format easily."),
        Tool("Code Helper", Icons.Default.Code, "ai_code", "Smart Utilities", Color(0xFF673AB7), isVisibleOnHome = false, isSubTool = true,  description = "Get AI-powered help with your coding tasks."),
        Tool("Data Visualizer", Icons.Default.BarChart, "data_viz", "Smart Utilities", Color(0xFF4CAF50), description = "Visualize your data with interactive charts."),
        Tool("Echo Remover", Icons.Default.SettingsBackupRestore, "echo_remover", "Smart Utilities", Color(0xFF009688), isVisibleOnHome = false, isSubTool = true, description = "Remove echo from your audio files."),
        Tool("Grammar Checker", Icons.Default.Spellcheck, "ai_grammar", "Smart Utilities", Color(0xFF4CAF50), isVisibleOnHome = false, isSubTool = true,  description = "Check and correct grammar in your text using AI."),
        Tool("Image Generator", Icons.Default.Image, "ai_image", "Smart Utilities", Color(0xFFFFC107), isVisibleOnHome = false, isSubTool = true,  description = "Generate stunning images from text prompts using AI."),
        Tool("Key BPM Finder", Icons.Default.MusicNote, "key_bpm_finder", "Smart Utilities", Color(0xFFF44336), description = "Find the key and BPM of any song."),
        Tool("Markdown Preview", Icons.Default.Description, "markdown_preview", "Smart Utilities", Color(0xFF3F51B5), description = "Preview your Markdown files in real-time."),
        Tool("Noise Remover", Icons.Default.Hearing, "ai_noise_remover", "Smart Utilities", Color(0xFF4CAF50), isVisibleOnHome = false, isSubTool = true, description = "AI-powered noise reduction for audio."),
        Tool("Object Detector", Icons.Default.CenterFocusStrong, "ai_obj_detect", "Smart Utilities", Color(0xFF673AB7), isVisibleOnHome = false, isSubTool = true,  description = "Detect objects in images using AI."),
        Tool("Regex Tester", Icons.Default.Code, "regex_tester", "Smart Utilities", Color(0xFF673AB7), description = "Test and debug your regular expressions."),
        Tool("Reverb Remover", Icons.Default.Waves, "reverb_remover", "Smart Utilities", Color(0xFF607D8B), isVisibleOnHome = false, isSubTool = true, description = "Remove reverb from your audio recordings."),
        Tool("Sentiment Analysis", Icons.Default.Mood, "ai_sentiment", "Smart Utilities", Color(0xFFFFC107), isVisibleOnHome = false, isSubTool = true,  description = "Analyze the sentiment of text using AI."),
        Tool("Smart Chat", Icons.AutoMirrored.Filled.Chat, "ai_chat", "Smart Utilities", Color(0xFF2196F3), isVisibleOnHome = false, isSubTool = true,  description = "Chat with an intelligent AI assistant."),
        Tool("Stems Splitter", Icons.AutoMirrored.Filled.AltRoute, "ai_stems_splitter", "Smart Utilities", Color(0xFF00BCD4), isVisibleOnHome = false, isSubTool = true, description = "Split songs into separate tracks (vocals, drums, etc.)."),
        Tool("Text Extractor", Icons.Default.Scanner, "ai_text_ext", "Smart Utilities", Color(0xFFE91E63), isVisibleOnHome = false, isSubTool = true,  description = "Extract text from images using AI OCR."),
        Tool("Text Summarizer", Icons.Default.Summarize, "ai_summarizer", "Smart Utilities", Color(0xFF4CAF50), isVisibleOnHome = false, isSubTool = true,  description = "Summarize long texts using AI."),
        Tool("Translator", Icons.Default.Translate, "ai_translate", "Smart Utilities", Color(0xFF2196F3), isVisibleOnHome = false, isSubTool = true,  description = "Translate text between languages using AI."),
        Tool("Video Noise Remover", Icons.Default.MovieFilter, "video_noise_remover", "Smart Utilities", Color(0xFF9C27B0), isVisibleOnHome = false, isSubTool = true, description = "Remove noise from your videos."),
        Tool("Vocal AutoTuner", Icons.Default.SettingsVoice, "vocal_autotuner", "Smart Utilities", Color(0xFFE91E63), isVisibleOnHome = false, isSubTool = true, description = "Apply auto-tune effects to vocals."),
        Tool("Vocal Remover", Icons.Default.PersonOff, "vocal_remover", "Smart Utilities", Color(0xFFFF9800), isVisibleOnHome = false, isSubTool = true, description = "Remove vocals from songs."),
        Tool("Voice Mimic", Icons.Default.RecordVoiceOver, "ai_voice_mimic", "Smart Utilities", Color(0xFF3F51B5), isVisibleOnHome = false, isSubTool = true,  description = "Mimic voices using AI."),

        // Audio & Music
        Tool("Audio Tools", Icons.Default.LibraryMusic, "audio_tools_group", "Audio & Music", Color(0xFF673AB7),
            description = "Comprehensive collection of audio editing and processing tools.",
            subToolRoutes = listOf("m_audio_editor", "m_audio_cutter", "m_audio_joiner", "m_audio_mixer", "m_audio_tag_editor", "m_audio_compressor", "m_audio_splitter", "m_audio_normalizer", "m_volume_booster", "m_speed_changer", "m_audio_pitch", "m_reverse_audio", "m_bass_booster", "m_echo_effect", "m_3d_audio", "m_audio_pan", "m_equalizer", "m_mute_audio", "m_silence_remover", "m_voice_changer", "m_karaoke_maker", "m_ringtone_maker", "m_text_to_speech", "m_speech_to_text", "noise_generator", "wave_generator", "silence_generator", "audio_loop", "sound_mastering", "add_sfx", "aud_conv", "aud_info_v2", "aud_eq_v2", "record_audio")),
        Tool("Metronome", Icons.Default.AvTimer, "metronome", "Audio & Music", Color(0xFF00BCD4), description = "A simple and precise metronome for musicians."),
        Tool("Guitar Tuner", Icons.Default.MusicNote, "guitar_tuner", "Audio & Music", Color(0xFFE91E63),  description = "Tune your guitar with high precision."),
        Tool("Chord Library", Icons.Default.LibraryMusic, "chord_lib", "Audio & Music", Color(0xFF673AB7),  description = "A comprehensive library of guitar chords."),
        Tool("Voice Memo", Icons.Default.SettingsVoice, "voice_memo", "Audio & Music", Color(0xFF2196F3),  description = "Record and organize your voice memos."),

        // Audio Sub-Tools
        Tool("Audio Editor", Icons.Default.Edit, "m_audio_editor", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Edit your audio files with ease."),
        Tool("Audio Cutter", Icons.Default.ContentCut, "m_audio_cutter", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Cut and trim audio segments."),
        Tool("Audio Joiner", Icons.Default.Link, "m_audio_joiner", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Merge multiple audio files into one."),
        Tool("Audio Mixer", Icons.Default.Tune, "m_audio_mixer", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Mix multiple audio tracks."),
        Tool("Audio Tag Editor", Icons.AutoMirrored.Filled.Label, "m_audio_tag_editor", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Edit ID3 tags of your music files."),
        Tool("Audio Compressor", Icons.Default.Compress, "m_audio_compressor", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Reduce audio file size without quality loss."),
        Tool("Audio Splitter", Icons.AutoMirrored.Filled.AltRoute, "m_audio_splitter", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Split audio into multiple parts."),
        Tool("Audio Normalizer", Icons.AutoMirrored.Filled.VolumeUp, "m_audio_normalizer", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Normalize audio volume levels."),
        Tool("Volume Booster", Icons.AutoMirrored.Filled.VolumeUp, "m_volume_booster", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Boost the volume of your audio."),
        Tool("Speed Changer", Icons.Default.FastForward, "m_speed_changer", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Change the playback speed of audio."),
        Tool("Pitch Changer", Icons.Default.Height, "m_audio_pitch", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Change the pitch of your audio."),
        Tool("Reverse Audio", Icons.Default.History, "m_reverse_audio", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Play your audio in reverse."),
        Tool("Bass Booster", Icons.Default.Speaker, "m_bass_booster", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Enhance the bass in your music."),
        Tool("Echo Effect", Icons.Default.SettingsBackupRestore, "m_echo_effect", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Add echo effects to your audio."),
        Tool("3D Audio", Icons.Default.Headset, "m_3d_audio", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Create an immersive 3D audio experience."),
        Tool("Audio Pan", Icons.AutoMirrored.Filled.AltRoute, "m_audio_pan", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Adjust the stereo panning of audio."),
        Tool("Equalizer", Icons.Default.Equalizer, "m_equalizer", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Fine-tune audio frequencies."),
        Tool("Mute Audio", Icons.AutoMirrored.Filled.VolumeOff, "m_mute_audio", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Mute specific parts of audio."),
        Tool("Silence Remover", Icons.Default.SpeakerNotesOff, "m_silence_remover", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Automatically remove silence from recordings."),
        Tool("Voice Changer", Icons.Default.Face, "m_voice_changer", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Change your voice with various effects."),
        Tool("Karaoke Maker", Icons.Default.Mic, "m_karaoke_maker", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Create karaoke tracks from songs."),
        Tool("Ringtone Maker", Icons.Default.Notifications, "m_ringtone_maker", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Create custom ringtones."),
        Tool("Text to Speech", Icons.Default.RecordVoiceOver, "m_text_to_speech", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Convert text into natural-sounding speech."),
        Tool("Speech to Text", Icons.Default.Mic, "m_speech_to_text", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Convert speech into written text."),
        Tool("Noise Generator", Icons.Default.GraphicEq, "noise_generator", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Generate various types of noise (white, pink, etc.)."),
        Tool("Wave Generator", Icons.Default.Waves, "wave_generator", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Generate audio waves at specific frequencies."),
        Tool("Silence Generator", Icons.Default.DoNotDisturbOn, "silence_generator", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Insert periods of silence into audio."),
        Tool("Audio Loop", Icons.Default.Loop, "audio_loop", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Create seamless audio loops."),
        Tool("Sound Mastering", Icons.Default.Insights, "sound_mastering", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Professional audio mastering tools."),
        Tool("Add SFX", Icons.Default.AutoAwesome, "add_sfx", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Add sound effects to your audio."),
        Tool("Audio Converter", Icons.Default.Transform, "aud_conv", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Convert audio between different formats."),
        Tool("Audio Info", Icons.Default.Info, "aud_info_v2", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "View detailed technical info of audio files."),
        Tool("Audio Equalizer", Icons.Default.Equalizer, "aud_eq_v2", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Advanced multi-band equalizer."),
        Tool("Record Audio", Icons.Default.Mic, "record_audio", "Audio & Music", isVisibleOnHome = false, isSubTool = true, description = "Record high-quality audio."),

        // Video & Media
        Tool("Video Tools", Icons.Default.VideoLibrary, "video_tools_group", "Video & Media", Color(0xFFF44336),
            description = "Professional video editing and processing tools.",
            subToolRoutes = listOf("video_trim", "video_compress", "video_reverse", "video_splitter", "mix_video_audio", "video_speed_changer", "video_sfx", "video_to_gif", "video_volume_booster", "video_delete", "video_silence", "video_loop", "video_flip", "video_stabilizer", "vid_annotator", "vid_thumb", "m_video_to_audio", "frame_grabber", "vid_edit_pro")),
        Tool("Audio Mastering", Icons.Default.GraphicEq, "aud_master_pro", "Video & Media", Color(0xFF673AB7),  description = "Advanced AI audio mastering suite."),
        Tool("Batch Image", Icons.Default.Collections, "batch_img_pro", "Video & Media", Color(0xFF4CAF50),  description = "Process multiple images at once."),
        Tool("Document Scanner", Icons.Default.Scanner, "doc_scanner", "Video & Media", Color(0xFF3F51B5),  description = "Scan documents and save as PDF."),
        Tool("Media Grabber", Icons.Default.Download, "media_grabber", "Video & Media", Color(0xFFFFC107), description = "Download media from various sources."),
        Tool("Perchance Tools", Icons.Default.AutoAwesome, "perchance_tools", "Video & Media", Color(0xFFE91E63),  description = "Access AI creative tools from Perchance.",
            subToolRoutes = listOf("per_image", "per_story", "per_character", "per_hub", "per_image_pro", "per_text_gen", "per_text_rewrite", "per_necs_story")),

        // Video Sub-Tools
        Tool("Video Editor", Icons.Default.Edit, "video_trim", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Trim and edit your videos."),
        Tool("Video Compressor", Icons.Default.Compress, "video_compress", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Reduce video file size."),
        Tool("Reverse Video", Icons.Default.History, "video_reverse", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Play your videos backwards."),
        Tool("Video Splitter", Icons.AutoMirrored.Filled.AltRoute, "video_splitter", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Split videos into segments."),
        Tool("Mix Video Audio", Icons.Default.Tune, "mix_video_audio", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Replace or mix video audio."),
        Tool("Video Speed", Icons.Default.FastForward, "video_speed_changer", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Change video playback speed."),
        Tool("Video SFX", Icons.Default.AutoAwesome, "video_sfx", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Add filters and effects to videos."),
        Tool("Video To GIF", Icons.Default.Gif, "video_to_gif", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Convert video clips to GIF format."),
        Tool("Video Volume", Icons.AutoMirrored.Filled.VolumeUp, "video_volume_booster", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Boost video audio volume."),
        Tool("Delete Segment", Icons.Default.Delete, "video_delete", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Remove unwanted parts from video."),
        Tool("Silence Video", Icons.AutoMirrored.Filled.VolumeOff, "video_silence", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Mute your videos completely."),
        Tool("Loop Video", Icons.Default.Loop, "video_loop", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Create seamless video loops."),
        Tool("Video Flip", Icons.Default.Flip, "video_flip", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Flip or rotate your videos."),
        Tool("Video Stabilizer", Icons.Default.Camera, "video_stabilizer", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Stabilize shaky video footage."),
        Tool("Video Frame Annotator", Icons.Default.Edit, "vid_annotator", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Draw and annotate on video frames."),
        Tool("Thumbnail Extractor", Icons.Default.Image, "vid_thumb", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Extract high-quality thumbnails from video."),
        Tool("Video to Audio", Icons.Default.VideoLibrary, "m_video_to_audio", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Extract audio from video files."),
        Tool("Video Frame Grabber", Icons.Default.CropOriginal, "frame_grabber", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Save individual frames as images."),

        // Perchance Sub-Tools
        Tool("Perchance Image Generator", Icons.Default.Image, "per_image", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Create stunning AI images with Perchance."),
        Tool("Perchance Story Writer", Icons.Default.AutoAwesome, "per_story", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Generate creative stories with Perchance."),
        Tool("Perchance Character Maker", Icons.Default.Person, "per_character", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Build unique AI characters with Perchance."),
        Tool("Perchance General Hub", Icons.Default.Hub, "per_hub", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Explore all tools in the Perchance platform."),
        Tool("AI Image Pro", Icons.Default.Image, "per_image_pro", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "Professional AI image generator by Perchance."),
        Tool("AI Text Gen", Icons.Default.TextFields, "per_text_gen", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "AI text generator by Perchance."),
        Tool("AI Text Rewriter", Icons.Default.Edit, "per_text_rewrite", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "AI text rewriter by Perchance."),
        Tool("NECS Story", Icons.Default.AutoAwesome, "per_necs_story", "Video & Media", isVisibleOnHome = false, isSubTool = true, description = "NECS story generator by Perchance."),

        // Image Tools
        Tool("Image Edit & Convert", Icons.Default.PhotoLibrary, "image_tools_group", "Image Tools", Color(0xFF2196F3),
            description = "Essential image editing, conversion, and optimization tools.",
            subToolRoutes = listOf("image_single_edit", "image_resize_conv", "image_format_conv", "image_crop", "image_cutting", "image_resize_weight", "image_resize_limits", "image_edit_exif", "image_delete_exif", "image_ai_tools", "image_bg_remover", "image_collage", "image_draw", "image_filter", "image_stacking", "image_stitching", "image_markup", "image_noise_gen", "image_watermark", "image_compare", "image_wallpapers", "image_to_svg", "image_web_load", "image_ocr", "image_preview", "image_base64", "image_palette", "image_color_picker", "image_mask_filter", "image_draw_bg", "image_layers_img", "image_layers_bg", "image_open_project", "multi_image_resize", "multi_crop", "pixel_art", "ascii_art")),
        Tool("APNG Tools", Icons.Default.Animation, "apng_tools", "Image Tools", Color(0xFF4CAF50),  description = "Tools for creating and managing APNG files.",
            subToolRoutes = listOf("image_to_apng", "apng_to_images", "apng_to_jxl")),
        Tool("Color & Palette Tools", Icons.Default.Palette, "color_palette_tools", "Image Tools", Color(0xFF00BCD4),  description = "Explore and manage colors and palettes.",
            subToolRoutes = listOf("color_info", "color_mixing", "color_harmonies", "color_shading", "image_histogram", "generate_palette", "material_you_palette", "edit_palette")),
        Tool("GIF Tools", Icons.Default.Animation, "gif_tools", "Image Tools", Color(0xFF9C27B0),  description = "Create and edit animated GIF files.",
            subToolRoutes = listOf("images_to_gif", "gif_to_images", "gif_to_jxl", "gif_to_webp")),
        Tool("JXL Tools", Icons.Default.Animation, "jxl_tools", "Image Tools", Color(0xFFFF9800),  description = "Tools for the modern JPEG XL format.",
            subToolRoutes = listOf("jpeg_to_jxl", "jxl_to_jpeg", "jxl_to_images", "images_to_jxl")),
        Tool("PDF Tools", Icons.Default.PictureAsPdf, "pdf_tools", "Image Tools", Color(0xFFF44336),  description = "The complete PDF toolkit.",
            subToolRoutes = listOf("pdf_preview", "images_to_pdf", "pdf_to_images", "pdf_merge", "pdf_split", "pdf_remove_pages", "pdf_rotate", "pdf_rearrange", "pdf_crop", "pdf_page_numbers", "pdf_watermark", "pdf_signature", "pdf_compress", "pdf_flatten", "pdf_print", "pdf_grayscale", "pdf_repair", "pdf_protect", "pdf_unlock", "pdf_metadata", "pdf_extract_images", "pdf_ocr", "pdf_zip")),
        Tool("WEBP Tools", Icons.Default.Animation, "webp_tools", "Image Tools", Color(0xFF2196F3),  description = "Efficient WEBP image management tools.",
            subToolRoutes = listOf("image_to_webp", "webp_to_images")),
        Tool("Exif Viewer", Icons.Default.CameraAlt, "exif_viewer", "Image Tools", Color(0xFF607D8B), description = "View and analyze image metadata."),
        Tool("Gradient Gen", Icons.Default.Gradient, "gradient_gen", "Image Tools", Color(0xFFFFEB3B), description = "Create beautiful gradients for your designs."),

        // Image Sub-Tools
        Tool("Single Edit", Icons.Default.Edit, "image_single_edit", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Basic image editing controls."),
        Tool("Resize and Convert", Icons.Default.PhotoSizeSelectLarge, "image_resize_conv", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Resize and change image format."),
        Tool("Format Conversion", Icons.Default.Transform, "image_format_conv", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Convert image between different types."),
        Tool("Crop", Icons.Default.Crop, "image_crop", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Crop your images to any size."),
        Tool("Image Cutting", Icons.Default.GridOn, "image_cutting", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Cut images into smaller pieces."),
        Tool("Resize by Weight", Icons.Default.Scale, "image_resize_weight", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Target a specific file size."),
        Tool("Resize by Limits", Icons.Default.AspectRatio, "image_resize_limits", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Resize within specified dimensions."),
        Tool("Edit EXIF", Icons.Default.CameraAlt, "image_edit_exif", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Edit your image's EXIF data."),
        Tool("Delete EXIF", Icons.Default.NoPhotography, "image_delete_exif", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Remove all metadata from image."),
        Tool("Smart Tools", Icons.Default.Psychology, "image_ai_tools", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "AI-powered image enhancements."),
        Tool("Background Remover", Icons.Default.LayersClear, "image_bg_remover", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Remove image background automatically."),
        Tool("Collage Maker", Icons.Default.AutoAwesomeMosaic, "image_collage", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Create beautiful photo collages."),
        Tool("Draw", Icons.Default.Brush, "image_draw", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Draw directly on your images."),
        Tool("Filter", Icons.Default.FilterHdr, "image_filter", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Apply professional filters."),
        Tool("Image Stacking", Icons.Default.Layers, "image_stacking", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Stack multiple images together."),
        Tool("Image Stitching", Icons.Default.ViewArray, "image_stitching", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Join images horizontally or vertically."),
        Tool("Markup Layers", Icons.Default.DashboardCustomize, "image_markup", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Add shapes and text layers."),
        Tool("Noise Generation", Icons.Default.BlurOn, "image_noise_gen", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Add grain or noise effects."),
        Tool("Watermarking", Icons.AutoMirrored.Filled.BrandingWatermark, "image_watermark", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Protect your images with watermarks."),
        Tool("Compare", Icons.Default.Compare, "image_compare", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Compare two images side-by-side."),
        Tool("Wallpapers Export", Icons.Default.Wallpaper, "image_wallpapers", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Save your current wallpaper."),
        Tool("Images to SVG", Icons.Default.Architecture, "image_to_svg", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Vectorize your images."),
        Tool("Web Image Loading", Icons.Default.CloudDownload, "image_web_load", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Load images from the web."),
        Tool("OCR", Icons.AutoMirrored.Filled.ManageSearch, "image_ocr", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Extract text from your pictures."),
        Tool("Image Preview", Icons.Default.Image, "image_preview", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Full-screen image viewer."),
        Tool("Base64 Tools", Icons.Default.Code, "image_base64", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Encode/Decode images to Base64."),
        Tool("Palette Tools", Icons.Default.ColorLens, "image_palette", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Extract colors from your images."),
        Tool("Color Picker", Icons.Default.Palette, "image_color_picker", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Pick any color from an image."),
        Tool("Mask Filter", Icons.Default.Texture, "image_mask_filter", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Apply custom masking effects."),
        Tool("Draw on background", Icons.Default.Brush, "image_draw_bg", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Draw on a solid color canvas."),
        Tool("Layers on image", Icons.Default.Layers, "image_layers_img", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Manage image overlays."),
        Tool("Layers on background", Icons.Default.Layers, "image_layers_bg", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Overlay images on a solid background."),
        Tool("Open project", Icons.Default.FolderOpen, "image_open_project", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Resume your previous editing project."),
        Tool("Multi Image Resize", Icons.Default.PhotoSizeSelectLarge, "multi_image_resize", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Resize a batch of images at once."),
        Tool("Multi Crop", Icons.Default.Crop, "multi_crop", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Crop multiple images together."),
        Tool("Pixel Art Maker", Icons.Default.Grid4x4, "pixel_art", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Turn your photos into pixel art."),
        Tool("ASCII Art", Icons.Default.Texture, "ascii_art", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Convert images to ASCII character art."),

        // PDF Sub-Tools
        Tool("Preview PDF", Icons.Default.Preview, "pdf_preview", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "High-quality PDF viewer."),
        Tool("PDF to Images", Icons.Default.Collections, "pdf_to_images", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Convert PDF pages to image files."),
        Tool("Merge PDF", Icons.Default.Merge, "pdf_merge", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Join multiple PDFs into one."),
        Tool("Split PDF", Icons.AutoMirrored.Filled.CallSplit, "pdf_split", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Extract pages from your PDF."),
        Tool("Remove PDF pages", Icons.Default.Delete, "pdf_remove_pages", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Delete specific pages from PDF."),
        Tool("Rotate PDF", Icons.AutoMirrored.Filled.RotateRight, "pdf_rotate", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Fix orientation of PDF pages."),
        Tool("Rearrange PDF", Icons.Default.Reorder, "pdf_rearrange", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Change the order of PDF pages."),
        Tool("Crop PDF", Icons.Default.Crop, "pdf_crop", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Trim the boundaries of PDF pages."),
        Tool("Page Numbers", Icons.Default.FormatListNumbered, "pdf_page_numbers", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Add page numbers to your document."),
        Tool("Watermarking PDF", Icons.AutoMirrored.Filled.BrandingWatermark, "pdf_watermark", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Apply watermarks to all PDF pages."),
        Tool("Signature", Icons.Default.Draw, "pdf_signature", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Sign your PDF documents electronically."),
        Tool("Compress PDF", Icons.Default.Compress, "pdf_compress", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Reduce PDF file size."),
        Tool("Flatten PDF", Icons.Default.LayersClear, "pdf_flatten", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Merge all PDF layers."),
        Tool("Print PDF", Icons.Default.Print, "pdf_print", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Print your PDF documents."),
        Tool("Grayscale PDF", Icons.Default.ColorLens, "pdf_grayscale", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Convert PDF to black and white."),
        Tool("Repair PDF", Icons.Default.Build, "pdf_repair", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Fix corrupted PDF files."),
        Tool("Protect PDF", Icons.Default.Lock, "pdf_protect", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Password-protect your PDF files."),
        Tool("Unlock PDF", Icons.Default.LockOpen, "pdf_unlock", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Remove password from protected PDFs."),
        Tool("PDF Metadata", Icons.Default.Info, "pdf_metadata", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Edit properties of PDF document."),
        Tool("Extract Images PDF", Icons.Default.Image, "pdf_extract_images", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Extract all images from a PDF."),
        Tool("PDF to Text (OCR)", Icons.Default.TextFields, "pdf_ocr", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Extract searchable text from PDF."),
        Tool("Zip PDF", Icons.Default.FolderZip, "pdf_zip", "Image Tools", isVisibleOnHome = false, isSubTool = true, description = "Split PDF and pack into ZIP."),

        // Other Sub-Tools
        Tool("Images to WEBP", Icons.Default.Transform, "image_to_webp", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("WEBP to images", Icons.Default.Collections, "webp_to_images", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to APNG", Icons.Default.Transform, "image_to_apng", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("APNG to images", Icons.Default.Collections, "apng_to_images", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("APNG to JXL", Icons.Default.Animation, "apng_to_jxl", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("JPEG to JXL", Icons.Default.Transform, "jpeg_to_jxl", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("JXL to JPEG", Icons.Default.Transform, "jxl_to_jpeg", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("JXL to Images", Icons.Default.Collections, "jxl_to_images", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to JXL", Icons.Default.Animation, "images_to_jxl", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to GIF", Icons.Default.Animation, "images_to_gif", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("GIF to images", Icons.Default.Collections, "gif_to_images", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("GIF to JXL", Icons.Default.Transform, "gif_to_jxl", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("GIF to WEBP", Icons.Default.Transform, "gif_to_webp", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Info", Icons.Default.Info, "color_info", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Mixing", Icons.Default.InvertColors, "color_mixing", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Harmonies", Icons.Default.Palette, "color_harmonies", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Shading", Icons.Default.Gradient, "color_shading", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Histogram", Icons.Default.BarChart, "image_histogram", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Generate Palette", Icons.Default.ColorLens, "generate_palette", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Material You", Icons.Default.AutoAwesome, "material_you_palette", "Image Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Edit Palette", Icons.Default.Edit, "edit_palette", "Image Tools", isVisibleOnHome = false, isSubTool = true),

        // Files & Documents
        Tool("Document Pro", Icons.Default.Description, "docs_group", "Files & Documents", Color(0xFF607D8B),
            description = "Advanced file and document management tools.",
            subToolRoutes = listOf("duplicate_finder", "file_explorer", "file_shredder", "storage_cleaner", "zip_unzip", "cipher_tools", "color_conv_pro", "crontab_gen", "port_checker", "sql_format")),

        // Files Sub-Tools
        Tool("Duplicate Finder", Icons.Default.ContentCopy, "duplicate_finder", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Find and remove duplicate files."),
        Tool("File Explorer", Icons.Default.Folder, "file_explorer", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Advanced local file explorer."),
        Tool("File Shredder", Icons.Default.DeleteForever, "file_shredder", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Securely delete files beyond recovery."),
        Tool("Storage Cleaner", Icons.Default.CleaningServices, "storage_cleaner", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Free up storage by removing junk files."),
        Tool("Zip/Unzip", Icons.Default.FolderZip, "zip_unzip", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Manage compressed archives."),
        Tool("Cipher", Icons.Default.Security, "cipher_tools", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Encrypt and decrypt your files."),
        Tool("Color Converter", Icons.Default.Palette, "color_conv_pro", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Convert between color spaces and formats."),
        Tool("Crontab Gen", Icons.Default.Schedule, "crontab_gen", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Generate cron expressions for scheduling."),
        Tool("Port Checker", Icons.Default.Dns, "port_checker", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Check status of specific network ports."),
        Tool("SQL Formatter", Icons.Default.Storage, "sql_format", "Files & Documents", isVisibleOnHome = false, isSubTool = true, description = "Beautify and format your SQL queries."),

        // Finance & Crypto
        Tool("Finance Tools", Icons.Default.MonetizationOn, "finance_group", "Finance & Crypto", Color(0xFFFF9800),
            description = "Complete set of financial calculators and trackers.",
            subToolRoutes = listOf("coin_tracker", "compound_interest", "crypto_conv", "currency_trends", "dividend_calc", "expense_tracker", "gst_calc", "inflation_calc", "loan_calc", "nft_viewer", "roi_calc", "retirement_planner", "sip_calc", "salary_calc", "stock_profit", "tax_calc", "wallet_explorer")),

        // Finance Sub-Tools
        Tool("Coin Tracker", Icons.Default.MonetizationOn, "coin_tracker", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Compound Interest", Icons.AutoMirrored.Filled.TrendingUp, "compound_interest", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Crypto Converter", Icons.Default.CurrencyExchange, "crypto_conv", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Currency Trends", Icons.Default.Timeline, "currency_trends", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Dividend Calc", Icons.Default.Payments, "dividend_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Expense Tracker", Icons.Default.AccountBalanceWallet, "expense_tracker", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("GST Calculator", Icons.Default.RequestQuote, "gst_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Inflation Calc", Icons.Default.MoneyOff, "inflation_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Loan Calculator", Icons.Default.AccountBalance, "loan_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("NFT Viewer", Icons.Default.Token, "nft_viewer", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("ROI Calculator", Icons.AutoMirrored.Filled.ShowChart, "roi_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Retirement Planner", Icons.Default.EventAvailable, "retirement_planner", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("SIP Calculator", Icons.Default.PieChart, "sip_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Salary Calc", Icons.Default.Work, "salary_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Stock Profit", Icons.AutoMirrored.Filled.TrendingUp, "stock_profit", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Tax Calculator", Icons.Default.MoneyOff, "tax_calc", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),
        Tool("Wallet Explorer", Icons.Default.AccountBalanceWallet, "wallet_explorer", "Finance & Crypto", isVisibleOnHome = false, isSubTool = true),

        // Health & Lifestyle
        Tool("Health & Lifestyle", Icons.Default.Favorite, "health_group", "Health & Lifestyle", Color(0xFFE91E63),
            description = "Track and improve your health and daily habits.",
            subToolRoutes = listOf("bmi", "bmr", "calorie_calc", "daily_journal", "daily_quotes", "egg_timer", "eye_exercise", "habit_tracker", "medication_tracker", "meditation", "period_tracker", "plant_care", "posture_check", "recipe_scaler", "sleep_tracker", "step_counter", "stretch_guide", "water_reminder", "water", "yoga_guide")),

        // Health Sub-Tools
        Tool("BMI Calc", Icons.Default.AccessibilityNew, "bmi", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("BMR Calculator", Icons.Default.Calculate, "bmr", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Calorie Calc", Icons.Default.Restaurant, "calorie_calc", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Daily Journal", Icons.Default.EditNote, "daily_journal", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Daily Quotes", Icons.Default.FormatQuote, "daily_quotes", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Egg Timer", Icons.Default.Timer, "egg_timer", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Eye Exercise", Icons.Default.Visibility, "eye_exercise", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Habit Tracker", Icons.Default.EventRepeat, "habit_tracker", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Medication Tracker", Icons.Default.MedicalServices, "medication_tracker", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Meditation Timer", Icons.Default.SelfImprovement, "meditation", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Period Tracker", Icons.Default.CalendarMonth, "period_tracker", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Plant Care", Icons.Default.Eco, "plant_care", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Posture Checker", Icons.Default.Accessibility, "posture_check", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Recipe Scaler", Icons.Default.Scale, "recipe_scaler", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Sleep Tracker", Icons.Default.Bedtime, "sleep_tracker", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Step Counter", Icons.AutoMirrored.Filled.DirectionsRun, "step_counter", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Stretching Guide", Icons.Default.SelfImprovement, "stretch_guide", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Water Reminder", Icons.Default.NotificationsActive, "water_reminder", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Water Tracker", Icons.Default.LocalDrink, "water", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),
        Tool("Yoga Guide", Icons.Default.SelfImprovement, "yoga_guide", "Health & Lifestyle", isVisibleOnHome = false, isSubTool = true),

        // Science & Education
        Tool("Science Lab", Icons.Default.Science, "science_group", "Science & Education", Color(0xFF4CAF50),
            description = "Explore the world through science and maps.",
            subToolRoutes = listOf("constants", "constellations", "dna_viz", "eq_solver", "force_calc", "physics_formulas", "fraction_calc", "matrix_calc", "periodic_table", "planet_finder", "pokedex", "prime", "solar_system", "star_map", "stats", "truth_table", "world_map")),

        // Science Sub-Tools
        Tool("Constants Table", Icons.Default.Functions, "constants", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Constellations", Icons.Default.Stars, "constellations", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("DNA Visualizer", Icons.Default.Hub, "dna_viz", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Force Calculator", Icons.Default.Speed, "force_calc", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Formula Sheet", Icons.Default.Functions, "physics_formulas", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Periodic Table", Icons.Default.GridOn, "periodic_table", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Planet Finder", Icons.Default.BrightnessHigh, "planet_finder", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Pokedex", Icons.Default.CatchingPokemon, "pokedex", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Prime Checker", Icons.Default.Filter7, "prime", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Solar System", Icons.Default.Public, "solar_system", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Star Map", Icons.Default.AutoAwesome, "star_map", "Science & Education", isVisibleOnHome = false, isSubTool = true),
        Tool("World Map", Icons.Default.Map, "world_map", "Science & Education", isVisibleOnHome = false, isSubTool = true),

        // Engineering
        Tool("Engineering Hub", Icons.Default.Architecture, "engineering_group", "Engineering", Color(0xFF607D8B),
            description = "Calculators and tools for engineers and makers.",
            subToolRoutes = listOf("antenna_calc", "circuit_calc", "device_discovery", "filter_design", "logic_gates", "mqtt_tester", "ohms_law", "pcb_trace", "resistor_code", "signal_gen_pro", "smart_hub", "wifi_anal", "wake_on_lan")),

        // Engineering Sub-Tools
        Tool("Antenna Calc", Icons.Default.SettingsInputAntenna, "antenna_calc", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Circuit Calc", Icons.Default.Memory, "circuit_calc", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Device Discovery", Icons.Default.Search, "device_discovery", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Filter Designer", Icons.Default.FilterList, "filter_design", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Logic Gates", Icons.Default.SettingsInputComponent, "logic_gates", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("MQTT Tester", Icons.Default.NetworkCheck, "mqtt_tester", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Ohm's Law", Icons.Default.ElectricalServices, "ohms_law", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("PCB Trace Width", Icons.Default.Straighten, "pcb_trace", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Resistor Color Code", Icons.Default.Architecture, "resistor_code", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Signal Gen", Icons.Default.GraphicEq, "signal_gen_pro", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Smart Hub", Icons.Default.Hub, "smart_hub", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("WIFI Analyzer", Icons.Default.Wifi, "wifi_anal", "Engineering", isVisibleOnHome = false, isSubTool = true),
        Tool("Wake On LAN", Icons.Default.SettingsPower, "wake_on_lan", "Engineering", isVisibleOnHome = false, isSubTool = true),

        // Outdoor & Nature
        Tool("Outdoor Tools", Icons.Default.Landscape, "outdoor_group", "Outdoor & Nature", Color(0xFF8BC34A),
            description = "Essential tools for outdoor enthusiasts.",
            subToolRoutes = listOf("air_quality", "altimeter", "altitude_graph", "area_calc", "campfire_guide", "compass", "sos", "gps_status", "hiking_trails", "knots_guide", "light_pollution", "moon_phase", "rain_radar", "route_planner", "signal_mirror", "uv_index", "weather_forecast")),

        // Outdoor Sub-Tools
        Tool("Air Quality", Icons.Default.Air, "air_quality", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Altitude Graph", Icons.AutoMirrored.Filled.ShowChart, "altitude_graph", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Area Calculator", Icons.Default.SquareFoot, "area_calc", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Campfire Guide", Icons.Default.LocalFireDepartment, "campfire_guide", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Emergency SOS", Icons.Default.Sos, "sos", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("GPS Status", Icons.Default.GpsFixed, "gps_status", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Hiking Trails", Icons.AutoMirrored.Filled.DirectionsRun, "hiking_trails", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Knots Guide", Icons.Default.InvertColors, "knots_guide", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Light Pollution", Icons.Default.NightsStay, "light_pollution", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Moon Phase", Icons.Default.Brightness3, "moon_phase", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Rain Radar", Icons.Default.Water, "rain_radar", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Route Planner", Icons.Default.Directions, "route_planner", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Signal Mirror", Icons.Default.FlashlightOn, "signal_mirror", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("UV Index", Icons.Default.WbSunny, "uv_index", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),
        Tool("Weather Forecast", Icons.Default.WbCloudy, "weather_forecast", "Outdoor & Nature", isVisibleOnHome = false, isSubTool = true),

        // System & Sensors
        Tool("System Lab", Icons.Default.Dns, "system_group", "System & Sensors", Color(0xFF673AB7),
            description = "Monitor system health and sensor data.",
            subToolRoutes = listOf("altimeter", "app_info", "barometer", "battery", "cpu_info", "compass", "device", "gforce_meter", "device_id", "level", "light", "metal", "process_manager", "spl_meter", "sensor_data", "sensors_list", "storage", "system_lab", "thermal_info", "update_check", "app_locker", "app_permissions", "perm_manager", "privacy_check")),

        // System Sub-Tools
        Tool("Altimeter", Icons.Default.Landscape, "altimeter", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("App Info", Icons.Default.Apps, "app_info", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Barometer", Icons.Default.Compress, "barometer", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Battery", Icons.Default.BatteryFull, "battery", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("CPU Info", Icons.Default.Memory, "cpu_info", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Compass", Icons.Default.Explore, "compass", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Device Info", Icons.Default.Info, "device", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("G-Force Meter", Icons.Default.Speed, "gforce_meter", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Hardware ID", Icons.Default.PermDeviceInformation, "device_id", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Level", Icons.Default.Architecture, "level", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Light Meter", Icons.Default.LightMode, "light", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Metal Detector", Icons.Default.CompassCalibration, "metal", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Process Manager", Icons.Default.Dns, "process_manager", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("SPL Meter", Icons.AutoMirrored.Filled.VolumeUp, "spl_meter", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Sensor Data", Icons.Default.SettingsInputComponent, "sensor_data", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Sensors List", Icons.AutoMirrored.Filled.List, "sensors_list", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Storage", Icons.Default.Storage, "storage", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("System Lab Core", Icons.Default.Science, "system_lab", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Thermal Info", Icons.Default.DeviceThermostat, "thermal_info", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Update Check", Icons.Default.SystemUpdate, "update_check", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("App Locker", Icons.Default.Lock, "app_locker", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("App Permissions", Icons.Default.Security, "app_permissions", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Permission Manager", Icons.Default.ManageAccounts, "perm_manager", "System & Sensors", isVisibleOnHome = false, isSubTool = true),
        Tool("Privacy Check", Icons.Default.PrivacyTip, "privacy_check", "System & Sensors", isVisibleOnHome = false, isSubTool = true),

        // Productivity
        Tool("Task Center", Icons.Default.Task, "prod_group", "Productivity", Color(0xFF4CAF50),
            description = "Stay organized and productive.",
            subToolRoutes = listOf("checklist", "kanban", "note", "pomodoro", "task_board", "time_logger", "daily_journal", "password_manager")),

        // Productivity Sub-Tools
        Tool("Checklist", Icons.Default.Checklist, "checklist", "Productivity", isVisibleOnHome = false, isSubTool = true),
        Tool("Kanban Board", Icons.Default.ViewWeek, "kanban", "Productivity", isVisibleOnHome = false, isSubTool = true),
        Tool("Note Pad", Icons.Default.NoteAlt, "note", "Productivity", isVisibleOnHome = false, isSubTool = true),
        Tool("Pomodoro", Icons.Default.HourglassEmpty, "pomodoro", "Productivity", isVisibleOnHome = false, isSubTool = true),
        Tool("Task Board", Icons.Default.Dashboard, "task_board", "Productivity", isVisibleOnHome = false, isSubTool = true),
        Tool("Time Logger", Icons.Default.HistoryToggleOff, "time_logger", "Productivity", isVisibleOnHome = false, isSubTool = true),
        Tool("Password Manager", Icons.Default.Password, "password_manager", "Productivity", isVisibleOnHome = false, isSubTool = true),

        // Developer
        Tool("Dev Expert", Icons.Default.Code, "dev_group", "Developer", Color(0xFF3F51B5),
            description = "Advanced tools for developers.",
            subToolRoutes = listOf("ascii_table", "base64", "hex_viewer", "json", "jwt_tool", "subnet_calc", "url_encoder", "yaml_to_json")),

        // Developer Sub-Tools
        Tool("ASCII Table", Icons.Default.Notes, "ascii_table", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Base64 Tool", Icons.Default.Code, "base64", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Hex Viewer", Icons.Default.Numbers, "hex_viewer", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("JSON Format", Icons.Default.DataObject, "json", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("JWT Tool", Icons.Default.Key, "jwt_tool", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Subnet Calc", Icons.Default.SettingsEthernet, "subnet_calc", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("URL Encoder", Icons.Default.Link, "url_encoder", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("YAML to JSON", Icons.Default.Transform, "yaml_to_json", "Developer", isVisibleOnHome = false, isSubTool = true),

        // Text
        Tool("Text Mastery", Icons.Default.TextFields, "text_group", "Text", Color(0xFF9C27B0),
            description = "Powerful tools for text processing.",
            subToolRoutes = listOf("ascii_art", "anagram", "case_converter", "lorem", "morse", "morse_decoder", "text_diff", "word_counter")),

        // Text Sub-Tools
        Tool("Anagram Finder", Icons.Default.SortByAlpha, "anagram", "Text", isVisibleOnHome = false, isSubTool = true),
        Tool("Case Converter", Icons.Default.TextFields, "case_converter", "Text", isVisibleOnHome = false, isSubTool = true),
        Tool("Lorem Ipsum", Icons.AutoMirrored.Filled.Notes, "lorem", "Text", isVisibleOnHome = false, isSubTool = true),
        Tool("Morse Code", Icons.Default.Language, "morse", "Text", isVisibleOnHome = false, isSubTool = true),
        Tool("Morse Decoder", Icons.Default.Language, "morse_decoder", "Text", isVisibleOnHome = false, isSubTool = true),
        Tool("Text Diff", Icons.Default.Difference, "text_diff", "Text", isVisibleOnHome = false, isSubTool = true),
        Tool("Word Counter", Icons.Default.Abc, "word_counter", "Text", isVisibleOnHome = false, isSubTool = true),

        // Calculation
        Tool("Advanced Math", Icons.Default.Functions, "math_group", "Calculation", Color(0xFF607D8B),
            description = "Calculators for every scenario.",
            subToolRoutes = listOf("binary_calc", "calculator", "date_calc", "discount", "fuel", "mortgage_calc", "sci_calc", "tip", "matrix_calc", "eq_solver", "fraction_calc", "truth_table", "stats")),

        // Calculation Sub-Tools
        Tool("Binary Calc", Icons.Default.Numbers, "binary_calc", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Basic Calculator", Icons.Default.Calculate, "calculator", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Date Calc", Icons.Default.CalendarToday, "date_calc", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Discount Calc", Icons.Default.Percent, "discount", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Fuel Cost", Icons.Default.LocalGasStation, "fuel", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Mortgage Calc", Icons.Default.Home, "mortgage_calc", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Scientific Calc", Icons.Default.Functions, "sci_calc", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Tip Calc", Icons.Default.Receipt, "tip", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Matrix Calc", Icons.Default.Grid4x4, "matrix_calc", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Equation Solver", Icons.Default.Functions, "eq_solver", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Fraction Calc", Icons.Default.Percent, "fraction_calc", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Truth Table Gen", Icons.Default.ListAlt, "truth_table", "Calculation", isVisibleOnHome = false, isSubTool = true),
        Tool("Statistics", Icons.Default.BarChart, "stats", "Calculation", isVisibleOnHome = false, isSubTool = true),

        // Conversion
        Tool("Ultimate Converter", Icons.Default.SwapHoriz, "conv_group", "Conversion", Color(0xFF2196F3),
            description = "Convert anything to anything.",
            subToolRoutes = listOf("base_conv", "currency", "torque_conv", "converter", "crypto_conv")),

        // Conversion Sub-Tools
        Tool("Base Converter", Icons.Default.Numbers, "base_conv", "Conversion", isVisibleOnHome = false, isSubTool = true),
        Tool("Currency Converter", Icons.Default.CurrencyExchange, "currency", "Conversion", isVisibleOnHome = false, isSubTool = true),
        Tool("Torque Converter", Icons.Default.SyncAlt, "torque_conv", "Conversion", isVisibleOnHome = false, isSubTool = true),
        Tool("Unit Converter", Icons.Default.SwapHoriz, "converter", "Conversion", isVisibleOnHome = false, isSubTool = true),

        // Network
        Tool("Network Lab", Icons.Default.NetworkCheck, "net_group", "Network", Color(0xFF00BCD4),
            description = "Network diagnostic and info tools.",
            subToolRoutes = listOf("dns_lookup", "my_ip", "network_info", "ping", "port_scanner", "speed_test", "whois", "subnet_calc", "route_planner", "device_discovery", "mqtt_tester")),

        // Network Sub-Tools
        Tool("DNS Lookup", Icons.Default.Dns, "dns_lookup", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("My IP", Icons.Default.Public, "my_ip", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Network Details", Icons.Default.NetworkCheck, "network_info", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Ping", Icons.Default.SettingsEthernet, "ping", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Port Scanner", Icons.Default.Search, "port_scanner", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Speed Test", Icons.Default.Speed, "speed_test", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Whois", Icons.Default.QuestionMark, "whois", "Network", isVisibleOnHome = false, isSubTool = true),

        // Utility & Misc
        Tool("Daily Helpers", Icons.Default.Build, "util_group", "Utility & Misc", Color(0xFF4CAF50),
            description = "Handy tools for everyday tasks.",
            subToolRoutes = listOf("bpm", "bio_linker", "car_maintenance", "clock", "coin_flip", "dice_roller", "flashlight", "fuel_consumption", "hub", "memory_game", "number_guessing", "protractor", "qr_gen", "random", "ruler", "social_preview", "speedometer", "stopwatch", "tic_tac_toe", "tiles_widgets", "unit_price", "vibration", "web", "world_clock", "qr_scanner")),

        // Utility Sub-Tools
        Tool("BPM Counter", Icons.Default.Favorite, "bpm", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Bio Linker", Icons.Default.Link, "bio_linker", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Car Maintenance", Icons.Default.Build, "car_maintenance", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Clock", Icons.Default.Schedule, "clock", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Coin Flip", Icons.Default.Paid, "coin_flip", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Dice Roller", Icons.Default.Casino, "dice_roller", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Flashlight", Icons.Default.FlashlightOn, "flashlight", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Fuel Consumption", Icons.Default.LocalGasStation, "fuel_consumption", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("nHub", Icons.Default.Hub, "hub", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Memory Game", Icons.Default.Extension, "memory_game", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Number Guessing", Icons.Default.QuestionMark, "number_guessing", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Protractor", Icons.Default.Architecture, "protractor", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("QR Generator", Icons.Default.QrCode, "qr_gen", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Random Gen", Icons.Default.Casino, "random", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Ruler", Icons.Default.Straighten, "ruler", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Social Preview", Icons.Default.Share, "social_preview", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Speedometer", Icons.Default.Speed, "speedometer", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Stopwatch", Icons.Default.Timer, "stopwatch", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Tic Tac Toe", Icons.Default.Close, "tic_tac_toe", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Nature Tiles", Icons.Default.Widgets, "tiles_widgets", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Unit Price Calc", Icons.Default.PriceCheck, "unit_price", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Vibration Test", Icons.Default.Vibration, "vibration", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("Web Search", Icons.Default.Search, "web", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("World Clock", Icons.Default.Public, "world_clock", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),
        Tool("QR Scanner", Icons.Default.QrCodeScanner, "qr_scanner", "Utility & Misc", isVisibleOnHome = false, isSubTool = true),

        // Social & Media
        Tool("Social & Media", Icons.Default.Share, "social_media_group", "Social & Media", Color(0xFFE91E63),
            description = "Tools for social media and media management.",
            subToolRoutes = listOf("social_preview", "bio_linker", "profile_photo_maker", "media_grabber")),
        Tool("Profile Photo Maker", Icons.Default.AccountCircle, "profile_photo_maker", "Social & Media", isVisibleOnHome = false, isSubTool = true, description = "Create perfect profile pictures."),

        // Privacy & Security
        Tool("Privacy & Security", Icons.Default.Security, "security_group", "Privacy & Security", Color(0xFF607D8B),
            description = "Protect your digital life.",
            subToolRoutes = listOf("password_manager", "password_gen", "app_locker", "cipher_tools", "file_shredder")),
        Tool("Strong Password Gen", Icons.Default.VpnKey, "password_gen", "Privacy & Security", isVisibleOnHome = false, isSubTool = true, description = "Generate unhackable passwords."),

        // DIY & Home
        Tool("DIY & Home", Icons.Default.Home, "diy_home_group", "DIY & Home", Color(0xFF795548),
            description = "Handy tools for home projects and maintenance.",
            subToolRoutes = listOf("level", "ruler", "protractor", "metal", "light", "unit_compare")),
        Tool("Unit Price Comparison", Icons.Default.CompareArrows, "unit_compare", "DIY & Home", isVisibleOnHome = false, isSubTool = true, description = "Compare prices for the best value."),

        // Travel & Maps
        Tool("Travel & Maps", Icons.Default.Flight, "travel_maps_group", "Travel & Maps", Color(0xFF03A9F4),
            description = "Essential tools for your next adventure.",
            subToolRoutes = listOf("world_clock", "currency", "travel_budget", "route_planner", "world_map")),
        Tool("Travel Budgeter", Icons.Default.AttachMoney, "travel_budget", "Travel & Maps", isVisibleOnHome = false, isSubTool = true, description = "Plan and track your travel expenses."),

        // Additional Tools in Utility & Misc
        Tool("Wifi QR Generator", Icons.Default.Wifi, "wifi_qr", "Utility & Misc", isVisibleOnHome = false, isSubTool = true, description = "Generate QR codes for your Wifi network."),
        Tool("Metatag Analyzer", Icons.Default.Search, "meta_anal", "Utility & Misc", isVisibleOnHome = false, isSubTool = true, description = "Analyze website metatags for SEO.")
    )
}
