package com.naturetools.app.model

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector

enum class BadgeType { NONE, NEW, PREMIUM }

data class Tool(
    val name: String,
    val icon: ImageVector,
    val route: String,
    val category: String,
    val color: Color = Color.Unspecified,
    val badge: BadgeType = BadgeType.NONE,
    val description: String? = null,
    val isVisibleOnHome: Boolean = true,
    val subToolRoutes: List<String>? = null,
    val isSubTool: Boolean = false
)

object ToolProvider {
    val tools = listOf(
        // --- MAIN TOOLS (GROUP SCREENS) ---

        // MEDIA
        Tool("Audio Tools", Icons.Default.LibraryMusic, "audio_tools_group", "Media", Color(0xFFE91E63),
            description = "Audio editing and processing tools.",
            subToolRoutes = listOf("add_sfx", "aud_conv", "aud_eq_v2", "aud_info_v2", "audio_loop", "binaural", "bpm", "chord_lib", "guitar_tuner", "key_bpm_finder", "m_3d_audio", "m_audio_compressor", "m_audio_cutter", "m_audio_editor", "m_audio_joiner", "m_audio_mixer", "m_audio_normalizer", "m_audio_pan", "m_audio_pitch", "m_audio_splitter", "m_audio_tag_editor", "m_bass_booster", "m_echo_effect", "m_equalizer", "m_karaoke_maker", "m_mute_audio", "m_reverse_audio", "m_ringtone_maker", "m_silence_remover", "m_speech_to_text", "m_speed_changer", "m_text_to_speech", "m_voice_changer", "m_volume_booster", "metronome", "noise_generator", "record_audio", "silence_generator", "sound_mastering", "voice_memo", "wave_generator")),
        Tool("Video Tools", Icons.Default.VideoLibrary, "video_tools_group", "Media", Color(0xFFF44336),
            description = "Professional video processing tools.",
            subToolRoutes = listOf("frame_grabber", "m_video_to_audio", "mix_video_audio", "vid_annotator", "vid_edit_pro", "vid_thumb", "video_compress", "video_delete", "video_flip", "video_loop", "video_reverse", "video_sfx", "video_silence", "video_speed_changer", "video_splitter", "video_stabilizer", "video_to_gif", "video_trim", "video_volume_booster", "digital_magnifier", "mirror_tool")),
        Tool("Image Tools", Icons.Default.PhotoLibrary, "image_tools_group", "Media", Color(0xFF2196F3),
            description = "Image editing and optimization tools.",
            subToolRoutes = listOf("batch_img_pro", "exif_viewer", "image_ai_tools", "image_base64", "image_bg_remover", "image_collage", "image_color_picker", "image_compare", "image_crop", "image_cutting", "image_delete_exif", "image_draw", "image_draw_bg", "image_edit_exif", "image_filter", "image_format_conv", "image_layers_bg", "image_layers_img", "image_mask_filter", "image_noise_gen", "image_ocr", "image_open_project", "image_palette", "image_preview", "image_resize_conv", "image_resize_limits", "image_resize_weight", "image_single_edit", "image_stacking", "image_stitching", "image_to_svg", "image_to_webp", "image_wallpapers", "image_watermark", "image_web_load", "multi_crop", "multi_image_resize", "pixel_art", "profile_photo_maker", "webp_to_images", "file_conv")),
        Tool("GIF & Animation", Icons.Default.Animation, "gif_tools_group", "Media", Color(0xFF9C27B0),
            description = "Tools for GIF, APNG and JXL animations.",
            subToolRoutes = listOf("apng_to_images", "apng_to_jxl", "gif_to_images", "gif_to_jxl", "gif_to_webp", "image_to_apng", "images_to_apng", "images_to_gif", "images_to_jxl", "jpeg_to_jxl", "jxl_to_images", "jxl_to_jpeg")),

        // EDUCATION
        Tool("Science Lab", Icons.Default.Science, "science_group", "Education", Color(0xFF4CAF50),
            description = "Science and physics exploration tools.",
            subToolRoutes = listOf("constants", "constellations", "dna_viz", "eq_solver", "force_calc", "physics_formulas", "periodic_table", "planet_finder", "pokedex", "prime", "solar_system", "star_map", "unit_circle")),
        Tool("Math Tools", Icons.Default.Functions, "math_group", "Education", Color(0xFF607D8B),
            description = "Advanced mathematical calculators.",
            subToolRoutes = listOf("binary_calc", "fraction_calc", "matrix_calc", "sci_calc", "stats", "truth_table")),

        // UTILITIES
        Tool("Daily Helpers", Icons.Default.Build, "util_group", "Utilities", Color(0xFF4CAF50),
            description = "Everyday utility tools.",
            subToolRoutes = listOf("clock", "date_calc", "flashlight", "protractor", "qr_gen", "qr_scanner", "ruler", "stopwatch", "tiles_widgets", "vibration", "wifi_qr", "panchangam")),
        Tool("Productivity", Icons.Default.Task, "prod_group", "Utilities", Color(0xFF3F51B5),
            description = "Stay organized and focused.",
            subToolRoutes = listOf("checklist", "daily_journal", "daily_quotes", "kanban", "note", "pomodoro", "task_board", "time_logger")),
        Tool("Calculators", Icons.Default.Calculate, "calc_group", "Utilities", Color(0xFFFF9800),
            description = "Practical calculators for daily use.",
            subToolRoutes = listOf("calculator", "discount", "mortgage_calc", "tip", "unit_compare", "unit_price", "volume_calc")),
        Tool("Unit Converters", Icons.Default.SwapHoriz, "conv_group", "Utilities", Color(0xFF2196F3),
            description = "Convert between various units.",
            subToolRoutes = listOf("base_conv", "converter", "crypto_conv", "currency", "torque_conv")),
        Tool("Engineering", Icons.Default.Architecture, "engineering_group", "Utilities", Color(0xFF607D8B),
            description = "Specialized engineering calculators.",
            subToolRoutes = listOf("antenna_calc", "circuit_calc", "electronics_tools", "filter_design", "logic_gates", "ohms_law", "pcb_trace", "resistor_code", "signal_gen_pro", "smart_hub")),

        // GAMES
        Tool("Game Collection", Icons.Default.Gamepad, "game_group", "Games", Color(0xFFFF9800),
            description = "Simple offline games.",
            subToolRoutes = listOf("coin_flip", "dice_roller", "memory_game", "number_guessing", "random", "tic_tac_toe", "snake", "ludo", "carroms", "chess")),

        // DEVICE
        Tool("System Monitor", Icons.Default.Dns, "system_group", "Device", Color(0xFF607D8B),
            description = "Monitor hardware and system status.",
            subToolRoutes = listOf("app_info", "battery", "cpu_info", "device", "device_id", "process_manager", "storage", "system_lab", "update_check")),
        Tool("Sensors & Tools", Icons.Default.SettingsInputComponent, "sensor_group", "Device", Color(0xFF673AB7),
            description = "Access and test device sensors.",
            subToolRoutes = listOf("altimeter", "barometer", "compass", "gforce_meter", "level", "light", "metal", "sensor_data", "sensors_list", "spl_meter", "thermal_info")),

        // DOCUMENTS
        Tool("PDF Toolkit", Icons.Default.PictureAsPdf, "pdf_tools_group", "Documents", Color(0xFFF44336),
            description = "Comprehensive PDF editing tools.",
            subToolRoutes = listOf("images_to_pdf", "pdf_compress", "pdf_crop", "pdf_extract_images", "pdf_flatten", "pdf_grayscale", "pdf_merge", "pdf_metadata", "pdf_ocr", "pdf_page_numbers", "pdf_preview", "pdf_print", "pdf_protect", "pdf_rearrange", "pdf_remove_pages", "pdf_repair", "pdf_rotate", "pdf_signature", "pdf_split", "pdf_unlock", "pdf_watermark", "pdf_zip")),
        Tool("Office & Files", Icons.Default.Description, "docs_group", "Documents", Color(0xFF607D8B),
            description = "Manage documents and files.",
            subToolRoutes = listOf("ai_doc_translator", "csv_to_json", "doc_scanner", "duplicate_finder", "file_explorer", "file_shredder", "sql_format", "storage_cleaner", "zip_unzip", "docs_online")),

        // SECURITY
        Tool("Privacy & Security", Icons.Default.Security, "security_group", "Security", Color(0xFF607D8B),
            description = "Tools to keep your digital life safe.",
            subToolRoutes = listOf("app_locker", "app_permissions", "cipher_tools", "password_gen", "password_manager", "perm_manager", "privacy_check", "sec_adguard", "sec_nextdns", "sec_bitwarden", "sec_ente")),

        // WEB
        Tool("Web & Online", Icons.Default.Language, "web_tools_group", "Web", Color(0xFF2196F3),
            description = "Web exploration and SEO tools.",
            subToolRoutes = listOf("hub", "media_grabber", "meta_anal", "web")),
        Tool("Perchance AI Hub", Icons.Default.AutoAwesome, "perchance_tools", "Web", Color(0xFFE91E63),
            description = "Access AI creative tools from Perchance.",
            subToolRoutes = listOf("per_character", "per_hub", "per_image", "per_image_pro", "per_necs_story", "per_story", "per_text_gen", "per_text_rewrite")),

        // NETWORK
        Tool("Network Lab", Icons.Default.NetworkCheck, "net_group", "Network", Color(0xFF00BCD4),
            description = "Network diagnostic and info tools.",
            subToolRoutes = listOf("device_discovery", "dns_lookup", "mqtt_tester", "my_ip", "network_info", "ping", "port_checker", "port_scanner", "speed_test", "subnet_calc", "wake_on_lan", "whois", "wifi_anal")),

        // DATA
        Tool("Data Tools", Icons.Default.Storage, "data_tools_group", "Data", Color(0xFF009688),
            description = "Process and visualize data.",
            subToolRoutes = listOf("data_viz", "json", "yaml_to_json")),

        // AI TOOLS
        Tool("AI Expert", Icons.Default.AutoAwesome, "ai_group", "AI Tools", Color(0xFF673AB7),
            description = "Intelligent AI assistant tools.",
            subToolRoutes = listOf("ai_chat", "ai_code", "ai_doc_translator", "ai_grammar", "ai_image", "ai_noise_remover", "ai_obj_detect", "ai_sentiment", "ai_stems_splitter", "ai_summarizer", "ai_text_ext", "ai_translate", "ai_voice_mimic", "aud_master_pro", "audio_noise_remover", "echo_remover", "reverb_remover", "video_noise_remover", "vocal_autotuner", "vocal_remover")),

        // FINANCE
        Tool("Finance Hub", Icons.Default.MonetizationOn, "finance_group", "Finance", Color(0xFFFF9800),
            description = "Complete financial toolkit.",
            subToolRoutes = listOf("coin_tracker", "compound_interest", "currency_trends", "dividend_calc", "expense_tracker", "gst_calc", "inflation_calc", "loan_calc", "nft_viewer", "retirement_planner", "roi_calc", "salary_calc", "sip_calc", "stock_profit", "tax_calc", "wallet_explorer")),

        // HEALTH
        Tool("Health & Vitality", Icons.Default.Favorite, "health_group", "Health", Color(0xFFE91E63),
            description = "Track your health and habits.",
            subToolRoutes = listOf("bmi", "bmr", "calorie_calc", "eye_exercise", "habit_tracker", "medication_tracker", "meditation", "period_tracker", "posture_check", "sleep_tracker", "step_counter", "stretch_guide", "water", "water_reminder", "yoga_guide")),

        // WEATHER
        Tool("Weather Center", Icons.Default.Cloud, "weather_group", "Weather", Color(0xFF03A9F4),
            description = "Forecasts and environment data.",
            subToolRoutes = listOf("air_quality", "light_pollution", "moon_phase", "rain_radar", "uv_index", "weather_forecast")),

        // TRAVEL
        Tool("Travel & Adventure", Icons.Default.Landscape, "outdoor_group", "Travel", Color(0xFF8BC34A),
            description = "Essential tools for explorers.",
            subToolRoutes = listOf("altitude_graph", "area_calc", "campfire_guide", "gps_status", "hiking_trails", "knots_guide", "packing_list", "route_planner", "signal_mirror", "sos", "travel_budget", "world_clock", "world_map")),

        // DEVELOPER
        Tool("Dev Expert", Icons.Default.Code, "dev_group", "Developer", Color(0xFF3F51B5),
            description = "Advanced developer utilities.",
            subToolRoutes = listOf("ascii_table", "base_conv", "base64", "crontab_gen", "hex_viewer", "jwt_tool", "markdown_preview", "regex_tester", "url_encoder")),
        Tool("Text Mastery", Icons.Default.TextFields, "text_group", "Developer", Color(0xFF9C27B0),
            description = "Powerful text processing tools.",
            subToolRoutes = listOf("anagram", "case_converter", "lorem", "morse", "morse_decoder", "text_diff", "word_counter", "word_rank_calc")),

        // DESIGN
        Tool("Color & Design", Icons.Default.Palette, "color_palette_group", "Design", Color(0xFF00BCD4),
            description = "Design and palette exploration.",
            subToolRoutes = listOf("color_conv_pro", "color_harmonies", "color_info", "color_mixing", "color_shading", "edit_palette", "generate_palette", "image_histogram", "material_you_palette")),

        // DIY
        Tool("DIY & Home", Icons.Default.Home, "diy_home_group", "DIY", Color(0xFF795548),
            description = "Home maintenance and auto tools.",
            subToolRoutes = listOf("car_maintenance", "fuel", "fuel_consumption", "plant_care", "recipe_scaler", "speedometer")),

        // SOCIAL
        Tool("Social Presence", Icons.Default.Share, "social_media_group", "Social", Color(0xFFE91E63),
            description = "Manage your social profiles.",
            subToolRoutes = listOf("bio_linker", "profile_photo_maker", "social_preview")),


        // --- SUB-TOOLS (isVisibleOnHome = false, isSubTool = true) ---

        // MEDIA
        Tool("3D Audio", Icons.Default.Headset, "m_3d_audio", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Binaural Beats", Icons.Default.Headset, "binaural", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Add SFX", Icons.Default.AutoAwesome, "add_sfx", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("APNG to images", Icons.Default.Collections, "apng_to_images", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("APNG to JXL", Icons.Default.Animation, "apng_to_jxl", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Compressor", Icons.Default.Compress, "m_audio_compressor", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Converter", Icons.Default.Transform, "aud_conv", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Cutter", Icons.Default.ContentCut, "m_audio_cutter", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Editor", Icons.Default.Edit, "m_audio_editor", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Equalizer", Icons.Default.Equalizer, "aud_eq_v2", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Info", Icons.Default.Info, "aud_info_v2", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Joiner", Icons.Default.Link, "m_audio_joiner", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Loop", Icons.Default.Loop, "audio_loop", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Mixer", Icons.Default.Tune, "m_audio_mixer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Normalizer", Icons.AutoMirrored.Filled.VolumeUp, "m_audio_normalizer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Pan", Icons.AutoMirrored.Filled.AltRoute, "m_audio_pan", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Splitter", Icons.AutoMirrored.Filled.AltRoute, "m_audio_splitter", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Tag Editor", Icons.AutoMirrored.Filled.Label, "m_audio_tag_editor", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Background Remover", Icons.Default.LayersClear, "image_bg_remover", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Base64 Tools", Icons.Default.Code, "image_base64", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Bass Booster", Icons.Default.Speaker, "m_bass_booster", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Batch Image", Icons.Default.Collections, "batch_img_pro", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("BPM Counter", Icons.Default.Favorite, "bpm", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Chord Library", Icons.Default.LibraryMusic, "chord_lib", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Collage Maker", Icons.Default.AutoAwesomeMosaic, "image_collage", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Picker", Icons.Default.Palette, "image_color_picker", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Compare", Icons.Default.Compare, "image_compare", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Crop", Icons.Default.Crop, "image_crop", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Delete EXIF", Icons.Default.NoPhotography, "image_delete_exif", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Delete Segment", Icons.Default.Delete, "video_delete", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Digital Magnifier", Icons.Default.ZoomIn, "digital_magnifier", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Draw", Icons.Default.Brush, "image_draw", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Draw on background", Icons.Default.Brush, "image_draw_bg", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Echo Effect", Icons.Default.SettingsBackupRestore, "m_echo_effect", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Edit EXIF", Icons.Default.CameraAlt, "image_edit_exif", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Equalizer", Icons.Default.Equalizer, "m_equalizer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Exif Viewer", Icons.Default.CameraAlt, "exif_viewer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("File Format Converter", Icons.Default.Transform, "file_conv", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Filter", Icons.Default.FilterHdr, "image_filter", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Format Conversion", Icons.Default.Transform, "image_format_conv", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("GIF to images", Icons.Default.Collections, "gif_to_images", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("GIF to JXL", Icons.Default.Transform, "gif_to_jxl", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("GIF to WEBP", Icons.Default.Transform, "gif_to_webp", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Guitar Tuner", Icons.Default.MusicNote, "guitar_tuner", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Image Cutting", Icons.Default.GridOn, "image_cutting", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Image Preview", Icons.Default.Image, "image_preview", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Image Stacking", Icons.Default.Layers, "image_stacking", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Image Stitching", Icons.Default.ViewArray, "image_stitching", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Image to APNG", Icons.Default.Transform, "image_to_apng", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to APNG", Icons.Default.Transform, "images_to_apng", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to GIF", Icons.Default.Animation, "images_to_gif", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to JXL", Icons.Default.Animation, "images_to_jxl", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to SVG", Icons.Default.Architecture, "image_to_svg", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to WEBP", Icons.Default.Transform, "image_to_webp", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("JPEG to JXL", Icons.Default.Transform, "jpeg_to_jxl", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("JXL to images", Icons.Default.Collections, "jxl_to_images", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("JXL to JPEG", Icons.Default.Transform, "jxl_to_jpeg", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Karaoke Maker", Icons.Default.Mic, "m_karaoke_maker", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Key BPM Finder", Icons.Default.MusicNote, "key_bpm_finder", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Layers on background", Icons.Default.Layers, "image_layers_bg", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Layers on image", Icons.Default.Layers, "image_layers_img", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Loop Video", Icons.Default.Loop, "video_loop", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Mask Filter", Icons.Default.Texture, "image_mask_filter", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Metronome", Icons.Default.AvTimer, "metronome", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Mirror Tool", Icons.Default.CameraFront, "mirror_tool", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Mix Video Audio", Icons.Default.Tune, "mix_video_audio", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Multi Crop", Icons.Default.Crop, "multi_crop", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Multi Image Resize", Icons.Default.PhotoSizeSelectLarge, "multi_image_resize", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Mute Audio", Icons.AutoMirrored.Filled.VolumeOff, "m_mute_audio", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Noise Generation", Icons.Default.BlurOn, "image_noise_gen", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Noise Generator", Icons.Default.GraphicEq, "noise_generator", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("OCR", Icons.AutoMirrored.Filled.ManageSearch, "image_ocr", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Open project", Icons.Default.FolderOpen, "image_open_project", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Palette Tools", Icons.Default.ColorLens, "image_palette", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Pitch Changer", Icons.Default.Height, "m_audio_pitch", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Pixel Art Maker", Icons.Default.Grid4x4, "pixel_art", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Record Audio", Icons.Default.Mic, "record_audio", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Resize and Convert", Icons.Default.PhotoSizeSelectLarge, "image_resize_conv", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Resize by Limits", Icons.Default.AspectRatio, "image_resize_limits", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Resize by Weight", Icons.Default.Scale, "image_resize_weight", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Reverse Audio", Icons.Default.History, "m_reverse_audio", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Reverse Video", Icons.Default.History, "video_reverse", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Ringtone Maker", Icons.Default.Notifications, "m_ringtone_maker", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Silence Generator", Icons.Default.DoNotDisturbOn, "silence_generator", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Silence Remover", Icons.Default.SpeakerNotesOff, "m_silence_remover", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Silence Video", Icons.AutoMirrored.Filled.VolumeOff, "video_silence", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Single Edit", Icons.Default.Edit, "image_single_edit", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Smart Tools", Icons.Default.Psychology, "image_ai_tools", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Sound Mastering", Icons.Default.Insights, "sound_mastering", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Speech to Text", Icons.Default.Mic, "m_speech_to_text", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Speed Changer", Icons.Default.FastForward, "m_speed_changer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Text to Speech", Icons.Default.RecordVoiceOver, "m_text_to_speech", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Thumbnail Extractor", Icons.Default.Image, "vid_thumb", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Compressor", Icons.Default.Compress, "video_compress", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Editor", Icons.Default.Edit, "video_trim", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Editor Pro", Icons.Default.Movie, "vid_edit_pro", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Flip", Icons.Default.Flip, "video_flip", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Frame Annotator", Icons.Default.Edit, "vid_annotator", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Frame Grabber", Icons.Default.CropOriginal, "frame_grabber", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video SFX", Icons.Default.AutoAwesome, "video_sfx", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Speed", Icons.Default.FastForward, "video_speed_changer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Splitter", Icons.AutoMirrored.Filled.AltRoute, "video_splitter", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Stabilizer", Icons.Default.Camera, "video_stabilizer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video to Audio", Icons.Default.VideoLibrary, "m_video_to_audio", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video To GIF", Icons.Default.Gif, "video_to_gif", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Volume", Icons.AutoMirrored.Filled.VolumeUp, "video_volume_booster", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Voice Changer", Icons.Default.Face, "m_voice_changer", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Voice Memo", Icons.Default.SettingsVoice, "voice_memo", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Volume Booster", Icons.AutoMirrored.Filled.VolumeUp, "m_volume_booster", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Wallpapers Export", Icons.Default.Wallpaper, "image_wallpapers", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Watermarking", Icons.AutoMirrored.Filled.BrandingWatermark, "image_watermark", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Wave Generator", Icons.Default.Waves, "wave_generator", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("Web Image Loading", Icons.Default.CloudDownload, "image_web_load", "Media", isVisibleOnHome = false, isSubTool = true),
        Tool("WEBP to images", Icons.Default.Collections, "webp_to_images", "Media", isVisibleOnHome = false, isSubTool = true),

        // EDUCATION
        Tool("Constants Table", Icons.Default.Functions, "constants", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Constellations", Icons.Default.Stars, "constellations", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("DNA Visualizer", Icons.Default.Hub, "dna_viz", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Equation Solver", Icons.Default.Functions, "eq_solver", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Force Calculator", Icons.Default.Speed, "force_calc", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Formula Sheet", Icons.Default.Functions, "physics_formulas", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Fraction Calc", Icons.Default.Percent, "fraction_calc", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Matrix Calc", Icons.Default.Grid4x4, "matrix_calc", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Periodic Table", Icons.Default.GridOn, "periodic_table", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Planet Finder", Icons.Default.BrightnessHigh, "planet_finder", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Pokedex", Icons.Default.CatchingPokemon, "pokedex", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Prime Checker", Icons.Default.Filter7, "prime", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Solar System", Icons.Default.Public, "solar_system", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Star Map", Icons.Default.AutoAwesome, "star_map", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Statistics", Icons.Default.BarChart, "stats", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Truth Table Gen", Icons.Default.ListAlt, "truth_table", "Education", isVisibleOnHome = false, isSubTool = true),
        Tool("Unit Circle", Icons.Default.InvertColors, "unit_circle", "Education", isVisibleOnHome = false, isSubTool = true),

        // UTILITIES
        Tool("Antenna Calc", Icons.Default.SettingsInputAntenna, "antenna_calc", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Base Converter", Icons.Default.Numbers, "base_conv", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Binary Calc", Icons.Default.Numbers, "binary_calc", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Calculator", Icons.Default.Calculate, "calculator", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Checklist", Icons.Default.Checklist, "checklist", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Circuit Calc", Icons.Default.Memory, "circuit_calc", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Clock", Icons.Default.Schedule, "clock", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Crypto Converter", Icons.Default.CurrencyExchange, "crypto_conv", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Currency Converter", Icons.Default.CurrencyExchange, "currency", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Daily Journal", Icons.Default.EditNote, "daily_journal", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Daily Quotes", Icons.Default.FormatQuote, "daily_quotes", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Date Calc", Icons.Default.CalendarToday, "date_calc", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Discount Calc", Icons.Default.Percent, "discount", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Electronics Tools", Icons.Default.ElectricalServices, "electronics_tools", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Filter Designer", Icons.Default.FilterList, "filter_design", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Flashlight", Icons.Default.FlashlightOn, "flashlight", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Kanban Board", Icons.Default.ViewWeek, "kanban", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Logic Gates", Icons.Default.SettingsInputComponent, "logic_gates", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Mortgage Calc", Icons.Default.Home, "mortgage_calc", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Nature Tiles", Icons.Default.Widgets, "tiles_widgets", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Note Pad", Icons.Default.NoteAlt, "note", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Ohm's Law", Icons.Default.ElectricalServices, "ohms_law", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Panchangam", Icons.Default.CalendarMonth, "panchangam", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("PCB Trace Width", Icons.Default.Straighten, "pcb_trace", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Pomodoro", Icons.Default.HourglassEmpty, "pomodoro", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Protractor", Icons.Default.Architecture, "protractor", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("QR Generator", Icons.Default.QrCode, "qr_gen", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("QR Scanner", Icons.Default.QrCodeScanner, "qr_scanner", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Resistor Color Code", Icons.Default.Architecture, "resistor_code", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Ruler", Icons.Default.Straighten, "ruler", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Scientific Calc", Icons.Default.Functions, "sci_calc", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Signal Gen", Icons.Default.GraphicEq, "signal_gen_pro", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Smart Hub", Icons.Default.Hub, "smart_hub", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Stopwatch", Icons.Default.Timer, "stopwatch", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Task Board", Icons.Default.Dashboard, "task_board", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Time Logger", Icons.Default.HistoryToggleOff, "time_logger", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Tip Calc", Icons.Default.Receipt, "tip", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Torque Converter", Icons.Default.SyncAlt, "torque_conv", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Unit Converter", Icons.Default.SwapHoriz, "converter", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Unit Price Calc", Icons.Default.PriceCheck, "unit_price", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Unit Price Comparison", Icons.AutoMirrored.Filled.CompareArrows, "unit_compare", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Vibration Test", Icons.Default.Vibration, "vibration", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Volume Calc", Icons.Default.VerticalAlignBottom, "volume_calc", "Utilities", isVisibleOnHome = false, isSubTool = true),
        Tool("Wifi QR Generator", Icons.Default.Wifi, "wifi_qr", "Utilities", isVisibleOnHome = false, isSubTool = true),

        // GAMES
        Tool("Carroms", Icons.Default.Gamepad, "carroms", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Chess", Icons.Default.Gamepad, "chess", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Coin Flip", Icons.Default.Paid, "coin_flip", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Dice Roller", Icons.Default.Casino, "dice_roller", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Ludo", Icons.Default.Gamepad, "ludo", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Memory Game", Icons.Default.Extension, "memory_game", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Number Guessing", Icons.Default.QuestionMark, "number_guessing", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Random Gen", Icons.Default.Casino, "random", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Snake", Icons.Default.Gamepad, "snake", "Games", isVisibleOnHome = false, isSubTool = true),
        Tool("Tic Tac Toe", Icons.Default.Close, "tic_tac_toe", "Games", isVisibleOnHome = false, isSubTool = true),

        // DEVICE
        Tool("Altimeter", Icons.Default.Landscape, "altimeter", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("App Info", Icons.Default.Apps, "app_info", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Barometer", Icons.Default.Compress, "barometer", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Battery", Icons.Default.BatteryFull, "battery", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Compass", Icons.Default.Explore, "compass", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("CPU Info", Icons.Default.Memory, "cpu_info", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Device Info", Icons.Default.Info, "device", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("G-Force Meter", Icons.Default.Speed, "gforce_meter", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Hardware ID", Icons.Default.PermDeviceInformation, "device_id", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Level", Icons.Default.Architecture, "level", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Light Meter", Icons.Default.LightMode, "light", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Metal Detector", Icons.Default.CompassCalibration, "metal", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Process Manager", Icons.Default.Dns, "process_manager", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Sensor Data", Icons.Default.SettingsInputComponent, "sensor_data", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Sensors List", Icons.AutoMirrored.Filled.List, "sensors_list", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("SPL Meter", Icons.AutoMirrored.Filled.VolumeUp, "spl_meter", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Storage", Icons.Default.Storage, "storage", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("System Lab Core", Icons.Default.Science, "system_lab", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Thermal Info", Icons.Default.DeviceThermostat, "thermal_info", "Device", isVisibleOnHome = false, isSubTool = true),
        Tool("Update Check", Icons.Default.SystemUpdate, "update_check", "Device", isVisibleOnHome = false, isSubTool = true),

        // DOCUMENTS
        Tool("Compress PDF", Icons.Default.Compress, "pdf_compress", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Crop PDF", Icons.Default.Crop, "pdf_crop", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("CSV to JSON", Icons.Default.Transform, "csv_to_json", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Doc Scanner", Icons.Default.Scanner, "doc_scanner", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Duplicate Finder", Icons.Default.ContentCopy, "duplicate_finder", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Extract Images PDF", Icons.Default.Image, "pdf_extract_images", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("File Explorer", Icons.Default.Folder, "file_explorer", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("File Shredder", Icons.Default.DeleteForever, "file_shredder", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Flatten PDF", Icons.Default.LayersClear, "pdf_flatten", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Grayscale PDF", Icons.Default.ColorLens, "pdf_grayscale", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Images to PDF", Icons.Default.Collections, "images_to_pdf", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Merge PDF", Icons.Default.Merge, "pdf_merge", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Page Numbers", Icons.Default.FormatListNumbered, "pdf_page_numbers", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("PDF Metadata", Icons.Default.Info, "pdf_metadata", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("PDF to Text (OCR)", Icons.Default.TextFields, "pdf_ocr", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Preview PDF", Icons.Default.Preview, "pdf_preview", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Print PDF", Icons.Default.Print, "pdf_print", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Protect PDF", Icons.Default.Lock, "pdf_protect", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Rearrange PDF", Icons.Default.Reorder, "pdf_rearrange", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Remove PDF pages", Icons.Default.Delete, "pdf_remove_pages", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Repair PDF", Icons.Default.Build, "pdf_repair", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Rotate PDF", Icons.AutoMirrored.Filled.RotateRight, "pdf_rotate", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Signature", Icons.Default.Draw, "pdf_signature", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Split PDF", Icons.AutoMirrored.Filled.CallSplit, "pdf_split", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("SQL Formatter", Icons.Default.Storage, "sql_format", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Online Document Tools", Icons.Default.Cloud, "docs_online", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Storage Cleaner", Icons.Default.CleaningServices, "storage_cleaner", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Unlock PDF", Icons.Default.LockOpen, "pdf_unlock", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Watermarking PDF", Icons.AutoMirrored.Filled.BrandingWatermark, "pdf_watermark", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Zip PDF", Icons.Default.FolderZip, "pdf_zip", "Documents", isVisibleOnHome = false, isSubTool = true),
        Tool("Zip/Unzip", Icons.Default.FolderZip, "zip_unzip", "Documents", isVisibleOnHome = false, isSubTool = true),

        // SECURITY
        Tool("App Locker", Icons.Default.Lock, "app_locker", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("App Permissions", Icons.Default.Security, "app_permissions", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("Cipher", Icons.Default.Security, "cipher_tools", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("Password Manager", Icons.Default.Password, "password_manager", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("Permission Manager", Icons.Default.ManageAccounts, "perm_manager", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("Privacy Check", Icons.Default.PrivacyTip, "privacy_check", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("Strong Password Gen", Icons.Default.VpnKey, "password_gen", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("AdGuard DNS", Icons.Default.Shield, "sec_adguard", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("NextDNS", Icons.Default.Dns, "sec_nextdns", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("Bitwarden", Icons.Default.Lock, "sec_bitwarden", "Security", isVisibleOnHome = false, isSubTool = true),
        Tool("Ente Auth", Icons.Default.VpnKey, "sec_ente", "Security", isVisibleOnHome = false, isSubTool = true),

        // WEB
        Tool("AI Image Pro", Icons.Default.Image, "per_image_pro", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Text Gen", Icons.Default.TextFields, "per_text_gen", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Text Rewriter", Icons.Default.Edit, "per_text_rewrite", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("Media Grabber", Icons.Default.Download, "media_grabber", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("Metatag Analyzer", Icons.Default.Search, "meta_anal", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("NECS Story", Icons.Default.AutoAwesome, "per_necs_story", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("nHub", Icons.Default.Hub, "hub", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("Perchance Character Maker", Icons.Default.Person, "per_character", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("Perchance General Hub", Icons.Default.Hub, "per_hub", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("Perchance Image Generator", Icons.Default.Image, "per_image", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("Perchance Story Writer", Icons.Default.AutoAwesome, "per_story", "Web", isVisibleOnHome = false, isSubTool = true),
        Tool("Web Search", Icons.Default.Search, "web", "Web", isVisibleOnHome = false, isSubTool = true),

        // NETWORK
        Tool("Device Discovery", Icons.Default.Search, "device_discovery", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("DNS Lookup", Icons.Default.Dns, "dns_lookup", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("MQTT Tester", Icons.Default.NetworkCheck, "mqtt_tester", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("My IP", Icons.Default.Public, "my_ip", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Network Details", Icons.Default.NetworkCheck, "network_info", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Ping", Icons.Default.SettingsEthernet, "ping", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Port Checker", Icons.Default.Dns, "port_checker", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Port Scanner", Icons.Default.Search, "port_scanner", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Speed Test", Icons.Default.Speed, "speed_test", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Subnet Calc", Icons.Default.SettingsEthernet, "subnet_calc", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Wake On LAN", Icons.Default.SettingsPower, "wake_on_lan", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("Whois", Icons.Default.QuestionMark, "whois", "Network", isVisibleOnHome = false, isSubTool = true),
        Tool("WIFI Analyzer", Icons.Default.Wifi, "wifi_anal", "Network", isVisibleOnHome = false, isSubTool = true),

        // DATA
        Tool("Data Visualizer", Icons.Default.BarChart, "data_viz", "Data", isVisibleOnHome = false, isSubTool = true),
        Tool("JSON Format", Icons.Default.DataObject, "json", "Data", isVisibleOnHome = false, isSubTool = true),
        Tool("YAML to JSON", Icons.Default.Transform, "yaml_to_json", "Data", isVisibleOnHome = false, isSubTool = true),

        // AI TOOLS
        Tool("AI Chat Assistant", Icons.Default.Chat, "ai_chat", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Code Helper", Icons.Default.Code, "ai_code", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Document Translator", Icons.Default.Translate, "ai_doc_translator", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Grammar Checker", Icons.Default.Spellcheck, "ai_grammar", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Image Generator", Icons.Default.Image, "ai_image", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Noise Remover", Icons.Default.BlurOff, "ai_noise_remover", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Object Detector", Icons.Default.CenterFocusStrong, "ai_obj_detect", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Sentiment Analysis", Icons.Default.Mood, "ai_sentiment", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Stems Splitter", Icons.Default.MusicNote, "ai_stems_splitter", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Text Summarizer", Icons.Default.Summarize, "ai_summarizer", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Text Extractor", Icons.Default.TextFields, "ai_text_ext", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("AI Translator", Icons.Default.Translate, "ai_translate", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Voice Mimic", Icons.Default.RecordVoiceOver, "ai_voice_mimic", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Master Pro", Icons.Default.SettingsVoice, "aud_master_pro", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Audio Noise Remover", Icons.Default.GraphicEq, "audio_noise_remover", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Echo Remover", Icons.Default.SettingsBackupRestore, "echo_remover", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Reverb Remover", Icons.Default.Waves, "reverb_remover", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Video Noise Remover", Icons.Default.VideoSettings, "video_noise_remover", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Vocal Autotuner", Icons.Default.MusicNote, "vocal_autotuner", "AI Tools", isVisibleOnHome = false, isSubTool = true),
        Tool("Vocal Remover", Icons.Default.MicOff, "vocal_remover", "AI Tools", isVisibleOnHome = false, isSubTool = true),

        // FINANCE
        Tool("Coin Tracker", Icons.Default.MonetizationOn, "coin_tracker", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Compound Interest", Icons.AutoMirrored.Filled.TrendingUp, "compound_interest", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Currency Trends", Icons.Default.Timeline, "currency_trends", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Dividend Calc", Icons.Default.Payments, "dividend_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Expense Tracker", Icons.Default.AccountBalanceWallet, "expense_tracker", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("GST Calculator", Icons.Default.RequestQuote, "gst_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Inflation Calc", Icons.Default.MoneyOff, "inflation_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Loan Calculator", Icons.Default.AccountBalance, "loan_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("NFT Viewer", Icons.Default.Token, "nft_viewer", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Retirement Planner", Icons.Default.EventAvailable, "retirement_planner", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("ROI Calculator", Icons.AutoMirrored.Filled.ShowChart, "roi_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Salary Calc", Icons.Default.Work, "salary_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("SIP Calculator", Icons.Default.PieChart, "sip_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Stock Profit", Icons.AutoMirrored.Filled.TrendingUp, "stock_profit", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Tax Calculator", Icons.Default.MoneyOff, "tax_calc", "Finance", isVisibleOnHome = false, isSubTool = true),
        Tool("Wallet Explorer", Icons.Default.AccountBalanceWallet, "wallet_explorer", "Finance", isVisibleOnHome = false, isSubTool = true),

        // HEALTH
        Tool("BMI Calc", Icons.Default.AccessibilityNew, "bmi", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("BMR Calculator", Icons.Default.Calculate, "bmr", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Calorie Calc", Icons.Default.Restaurant, "calorie_calc", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Eye Exercise", Icons.Default.Visibility, "eye_exercise", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Habit Tracker", Icons.Default.EventRepeat, "habit_tracker", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Medication Tracker", Icons.Default.MedicalServices, "medication_tracker", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Meditation Timer", Icons.Default.SelfImprovement, "meditation", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Period Tracker", Icons.Default.CalendarMonth, "period_tracker", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Posture Checker", Icons.Default.Accessibility, "posture_check", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Sleep Tracker", Icons.Default.Bedtime, "sleep_tracker", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Step Counter", Icons.AutoMirrored.Filled.DirectionsRun, "step_counter", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Stretching Guide", Icons.Default.SelfImprovement, "stretch_guide", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Water Reminder", Icons.Default.NotificationsActive, "water_reminder", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Water Tracker", Icons.Default.LocalDrink, "water", "Health", isVisibleOnHome = false, isSubTool = true),
        Tool("Yoga Guide", Icons.Default.SelfImprovement, "yoga_guide", "Health", isVisibleOnHome = false, isSubTool = true),

        // WEATHER
        Tool("Air Quality", Icons.Default.Air, "air_quality", "Weather", isVisibleOnHome = false, isSubTool = true),
        Tool("Light Pollution", Icons.Default.NightsStay, "light_pollution", "Weather", isVisibleOnHome = false, isSubTool = true),
        Tool("Moon Phase", Icons.Default.Brightness3, "moon_phase", "Weather", isVisibleOnHome = false, isSubTool = true),
        Tool("Rain Radar", Icons.Default.Water, "rain_radar", "Weather", isVisibleOnHome = false, isSubTool = true),
        Tool("UV Index", Icons.Default.WbSunny, "uv_index", "Weather", isVisibleOnHome = false, isSubTool = true),
        Tool("Weather Forecast", Icons.Default.WbCloudy, "weather_forecast", "Weather", isVisibleOnHome = false, isSubTool = true),

        // TRAVEL
        Tool("Altitude Graph", Icons.AutoMirrored.Filled.ShowChart, "altitude_graph", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Area Calculator", Icons.Default.SquareFoot, "area_calc", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Campfire Guide", Icons.Default.LocalFireDepartment, "campfire_guide", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Emergency SOS", Icons.Default.Sos, "sos", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("GPS Status", Icons.Default.GpsFixed, "gps_status", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Hiking Trails", Icons.AutoMirrored.Filled.DirectionsRun, "hiking_trails", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Knots Guide", Icons.Default.InvertColors, "knots_guide", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Packing List", Icons.Default.Checklist, "packing_list", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Route Planner", Icons.Default.Directions, "route_planner", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Signal Mirror", Icons.Default.FlashlightOn, "signal_mirror", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("Travel Budgeter", Icons.Default.AttachMoney, "travel_budget", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("World Clock", Icons.Default.Public, "world_clock", "Travel", isVisibleOnHome = false, isSubTool = true),
        Tool("World Map", Icons.Default.Map, "world_map", "Travel", isVisibleOnHome = false, isSubTool = true),

        // DEVELOPER
        Tool("Anagram Finder", Icons.Default.SortByAlpha, "anagram", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("ASCII Table", Icons.AutoMirrored.Filled.Notes, "ascii_table", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Base64 Tool", Icons.Default.Code, "base64", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Case Converter", Icons.Default.TextFields, "case_converter", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Crontab Gen", Icons.Default.Schedule, "crontab_gen", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Hex Viewer", Icons.Default.Numbers, "hex_viewer", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("JWT Tool", Icons.Default.Key, "jwt_tool", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Lorem Ipsum", Icons.AutoMirrored.Filled.Notes, "lorem", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Markdown Preview", Icons.Default.Description, "markdown_preview", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Morse Code", Icons.Default.Language, "morse", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Morse Decoder", Icons.Default.Language, "morse_decoder", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Regex Tester", Icons.Default.Code, "regex_tester", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Text Diff", Icons.Default.Difference, "text_diff", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("URL Encoder", Icons.Default.Link, "url_encoder", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Word Counter", Icons.Default.Abc, "word_counter", "Developer", isVisibleOnHome = false, isSubTool = true),
        Tool("Word Rank", Icons.Default.Calculate, "word_rank_calc", "Developer", isVisibleOnHome = false, isSubTool = true),

        // DESIGN
        Tool("Color Converter", Icons.Default.Palette, "color_conv_pro", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Harmonies", Icons.Default.Palette, "color_harmonies", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Info", Icons.Default.Info, "color_info", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Mixing", Icons.Default.InvertColors, "color_mixing", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Color Shading", Icons.Default.Gradient, "color_shading", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Edit Palette", Icons.Default.Edit, "edit_palette", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Generate Palette", Icons.Default.ColorLens, "generate_palette", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Histogram", Icons.Default.BarChart, "image_histogram", "Design", isVisibleOnHome = false, isSubTool = true),
        Tool("Material You", Icons.Default.AutoAwesome, "material_you_palette", "Design", isVisibleOnHome = false, isSubTool = true),

        // DIY
        Tool("Car Maintenance", Icons.Default.Build, "car_maintenance", "DIY", isVisibleOnHome = false, isSubTool = true),
        Tool("Fuel Consumption", Icons.Default.LocalGasStation, "fuel_consumption", "DIY", isVisibleOnHome = false, isSubTool = true),
        Tool("Fuel Cost", Icons.Default.LocalGasStation, "fuel", "DIY", isVisibleOnHome = false, isSubTool = true),
        Tool("Plant Care", Icons.Default.Eco, "plant_care", "DIY", isVisibleOnHome = false, isSubTool = true),
        Tool("Recipe Scaler", Icons.Default.Scale, "recipe_scaler", "DIY", isVisibleOnHome = false, isSubTool = true),
        Tool("Speedometer", Icons.Default.Speed, "speedometer", "DIY", isVisibleOnHome = false, isSubTool = true),

        // SOCIAL
        Tool("Bio Linker", Icons.Default.Link, "bio_linker", "Social", isVisibleOnHome = false, isSubTool = true),
        Tool("Profile Photo Maker", Icons.Default.AccountCircle, "profile_photo_maker", "Social", isVisibleOnHome = false, isSubTool = true),
        Tool("Social Preview", Icons.Default.Share, "social_preview", "Social", isVisibleOnHome = false, isSubTool = true)
    )
}
