# DeviceConnectionInfo - AzureSQL
[device_connection_info]
TargetServer=prathamcdpserver.database.windows.net
SchemaName=dbo
TargetDb=cdp_db
# TableName=Anomaly_input1
UserName=cdpadmin
Password=device@123

#Azure Anomaly Detection API
#Subscription Key: 2d7dbb8096db427baf915c9ae59f07b1
#Endpoint url: https://prathamanomalydetector.cognitiveservices.azure.com/