export const MenuConfig = {
  drawer_menu: [
    {
      id: 0,
      name: "reports_dashboards",
      route: "/reports",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
      subroutes: [],
    },
    {
      id: 1,
      name: "user_management",
      route: "/user_management",
      role: ["DP Admin"],
      subroutes: ["/add_user", "/delete_user"],
    },
    {
      id: 2,
      name: "project_management",
      route: "/project_management",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
      subroutes: [
        "/project_submanagement",
        "/proj_user_management",
        "/create_project",
        "/edit_project",
        "/provisioned_resourcedetails",
      ],
    },
    {
      id: 3,
      name: "resource_provisioning",
      route: "/resourceprovisioning",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
      subroutes: [
        "/kubernetes",
        "/airflow",
        "/airbyte",
        "/assignresource",
        "/deleteresource",
      ],
    },
    {
      id: 4,
      name: "data_science",
      route: "/datascience",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
      subroutes: [],
    },
    {
      id: 5,
      name: "data_services",
      route: "/dataservices",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
      subroutes: [],
    },
    {
      id: 6,
      name: "managed_finOps",
      route: "/costusage",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
      subroutes: ["/cost_charts", "/usage_charts"],
    },
    {
      id: 7,
      name: "central_config",
      route: "/central_config",
      role: ["DP Admin"],
      subroutes: ["/central_config/add_config", "/central_config/edit_config"],
    },
    { id: 8, name: "separator", separator: true, role: "All", subroutes: [] },
    { id: 9, name: "login", route: "/azure_login", role: "All", subroutes: [] },
  ],
  l0_menu: [
    {
      id: 0,
      name: "reports",
      route: "/reports",
      title: "Dashboard",
      text: "Explore and review Tableau and Power BI dashboards to visualize data from multiple sources and derive actionable insights.",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 1,
      name: "user-management",
      route: "/user_management",
      title: "User Management",
      text: "Control user access, on-board/ off-board users from the platform/ projects.",
      role: ["DP Admin"],
    },
    {
      id: 2,
      name: "project-management",
      route: "/project_management",
      title: "Project Management",
      text: " Create new projects, view details, edit and close existing projects.",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 3,
      name: "resource-provisioning",
      route: "/resourceprovisioning",
      title: "Resource Provisioning",
      text: "Provision cloud resources, Kubernetes Cluster and VMs for different projects.",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 4,
      name: "data-science",
      route: "/datascience",
      title: "Data Science",
      text: "Run analytics for industry specific use-cases based on requirements. Tools such as HCL's AION and other IP's are available for integration.",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
    },
    {
      id: 5,
      name: "data-services",
      route: "/dataservices",
      title: "Data Services",
      text: "Utilize various services such as Data Cataloging, Data Quality Check, Synthetic Data Generation and more to solve all your data needs.",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
    },
    {
      id: 6,
      name: "managed-finops",
      route: "/costusage",
      title: "FinOps Dashboard",
      text: "Gain control of unnecessary costs and find value in your cloud investment",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 7,
      name: "central-config",
      route: "/central_config",
      title: "Centralized Configuration",
      text: "Manage all the configurations and key-values pair used across the projects",
      role: ["DP Admin"],
    },
  ],
  all_urls: [],
};
