[[inputs.http_listener_v2]]
 ## Address and port to host HTTP listener on
 service_address = ":1234"
 ## Path to listen to.
 path = "/receive"
 ## Data format to consume.
 data_format = "prometheusremotewrite"


[[outputs.influxdb_v2]]
  urls = ["http://synergizer_influxdb:8086"]
  token = "XahfVyu0VH-cFxqe60UUvBg9WUJ1vrAF6mQFL6mHWgaEdLEPd_5kXRHfVqefWo_iVjhEUDSHqgqxBRNKXcVSig=="
  organization = "my-org"
  bucket = "my-bucket"



