# Generated by Django 3.2.11 on 2022-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=40, null=True)),
                ('execution_start', models.DateTimeField(auto_now_add=True)),
                ('execution_end', models.DateTimeField(null=True)),
                ('datasource_name', models.CharField(max_length=100)),
                ('rule_name', models.CharField(max_length=100)),
                ('run_name', models.CharField(max_length=100, null=True)),
                ('checkpoint_name', models.CharField(max_length=100, null=True)),
                ('source_dataset', models.CharField(max_length=100, null=True)),
                ('target_dataset', models.CharField(max_length=100)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_passed', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('results', models.TextField(null=True)),
                ('statistics', models.TextField(null=True)),
                ('success', models.BooleanField(null=True)),
                ('complete_result_url', models.URLField(null=True)),
            ],
        ),
    ]
