# Generated by Django 3.2.12 on 2022-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0005_auto_20220307_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='json',
            field=models.TextField(default=''),
        ),
    ]
