export const MenuConfig = {
  drawer_menu: [
    {
      id: 0,
      name: "reports_dashboards",
      route: "/reports",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 1,
      name: "resource_provisioning",
      route: "/resourceprovisioning",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 2,
      name: "data_science",
      route: "/datascience",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
    },
    {
      id: 3,
      name: "data_services",
      route: "/dataservices",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
    },
    {
      id: 4,
      name: "user_management",
      route: "/user_management",
      role: ["DP Admin"],
    },
    {
      id: 5,
      name: "project_management",
      route: "/project_management",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 6,
      name: "managed_finOps",
      route: "/costusage",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    { id: 7, name: "separator", separator: true, role: "All" },
    { id: 8, name: "login", route: "/azure_login", role: "All" },
  ],
  l0_menu: [
    {
      id: 0,
      name: "reports",
      route: "/reports",
      title: "Reports & Dashborads",
      text: "Explore and review Tableau and Power BI dashboards to visualize data from multiple sources and derive actionable insights.",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 1,
      name: "resource-provisioning",
      route: "/resourceprovisioning",
      title: "Resource Provisioning",
      text: "Raise a ticket, check ticket status or request a software, approve requests and check the status of your tickets.",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 2,
      name: "data-science",
      route: "/datascience",
      title: "Data Science",
      text: "Run analytics for industry specific use-cases based on requirements. Tools such as HCL's AION and other IP's are available for integration.",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
    },
    {
      id: 3,
      name: "data-services",
      route: "/dataservices",
      title: "Data Services",
      text: "Utilize various services such as Data Cataloging, Data Quality Check, Synthetic Data Generation and more to solve all your data needs.",
      role: ["Data Engineer - Team Lead", "Data Engineer - Team Member"],
    },
    {
      id: 4,
      name: "user-management",
      route: "/user_management",
      title: "User Management",
      text: "Control user access, on-board/ off-board users from the platform/ projects.",
      role: ["DP Admin"],
    },
    {
      id: 5,
      name: "project-management",
      route: "/project_management",
      title: "Project Management",
      text: " Create new projects, view details, edit and close existing projects.",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
    {
      id: 6,
      name: "managed-finops",
      route: "/managed_finops",
      title: "Managed FinOps",
      text: "text managed finops",
      role: [
        "DP Admin",
        "Data Engineer - Team Lead",
        "Data Engineer - Team Member",
      ],
    },
  ],
  all_urls: [],
};
