# Generated by Django 3.2.11 on 2022-02-14 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='execution_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
