# Generated by Django 3.2.12 on 2022-03-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0003_auto_20220307_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('batch', 'batch_data'), ('stream', 'stream_data')], max_length=40),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in-progress', 'Progress'), ('completed', 'Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.project')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='execution_id',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='ge_api.execution'),
        ),
    ]
