# Generated by Django 3.2.12 on 2022-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0004_auto_20220307_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqdimension',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='rulemodel',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='rulemodel',
            name='example',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rulemodel',
            name='json',
            field=models.TextField(default=''),
        ),
    ]
