[config]
# Database setting to fetch service principal credentials
server_name = prathamcdpsynapsews.sql.azuresynapse.net
database_name = cdp_device_pool
user_name = cdpadmin
password = device@123
prediction_table = aion_prediction_result
tenant_id = 189de737-c93a-4f5a-8b68-6f4ca9941912
client_id = 7c38f76b-c45e-4a9a-81b8-d8c57cccb5ad
client_secret = eEe7Q~Mtew.CQ0njKkYTJNjO3URb5DJiWegUq
storage_account_name = prathamdatalake
container_name = errordatazone
