# DeviceConnectionInfo - AzureSQL
[device_connection_info]
TargetServer=prathamcdpserver.database.windows.net
SchemaName=dbo
TargetDb=cdp_db
TableName=tblDeviceConnectionInfo
UserName=cdpadmin
Password=device@123

[anomaly_data]
temperature_min_threshold = 5,70
temperature_max_threshold = 100,120
humidity_min_threshold = 5,70
humidity_max_threshold = 100,120
volt_min_threshold = 5,80
volt_max_threshold = 260,320
rotate_min_threshold = 5,120
rotate_max_threshold = 700,1000
pressure_min_threshold = 5,50
pressure_max_threshold = 200,300
vibration_min_threshold = 5,50
vibration_max_threshold = 100,200

# Device_Status
[device_status]
time_interval = 5
# time_interval in mins
device_count=10
#event_start_time=09:33:00
event_start_time=now
event_stop_time=18:30:00


[config]
#device_count=10
#time_interval=10
# time_interval in seconds

[SDVMODELCONFIG]
#column_name=""
#column_name=Effective_Date
#column_name=Requested_Date
column_name=Time
num_records=1463





