package omni.toolbox.ui.screens.data

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ShowChart
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import omni.toolbox.ui.components.ToolScreen
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DataToolScreen(navController: NavHostController, route: String, toolName: String) {
    val context = LocalContext.current
    var selectedFileUri by remember { mutableStateOf<Uri?>(null) }
    var selectedFileName by remember { mutableStateOf<String?>(null) }
    var processing by remember { mutableStateOf(false) }
    var resultGenerated by remember { mutableStateOf(false) }
    val snackbarHostState = remember { SnackbarHostState() }
    val scope = rememberCoroutineScope()

    val filePickerLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.OpenDocument(),
        onResult = { uri ->
            selectedFileUri = uri
            selectedFileName = uri?.lastPathSegment
            resultGenerated = false
        }
    )

    // Data for processing
    val dataState = remember { mutableStateListOf<Map<String, String>>() }

    // Mock data fallback
    val mockData = remember {
        listOf(
            mapOf("id" to "1", "value" to "10", "label" to "A"),
            mapOf("id" to "2", "value" to "15", "label" to "B"),
            mapOf("id" to "3", "value" to "12", "label" to "C"),
            mapOf("id" to "4", "value" to "100", "label" to "D"), // Anomaly
            mapOf("id" to "5", "value" to "11", "label" to "E"),
            mapOf("id" to "6", "value" to "", "label" to "F"),    // Missing
            mapOf("id" to "7", "value" to "14", "label" to "G")
        )
    }

    Scaffold(
        snackbarHost = { SnackbarHost(snackbarHostState) },
        topBar = {
            TopAppBar(
                title = { Text(toolName) },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Icon(
                imageVector = getToolIcon(route),
                contentDescription = null,
                modifier = Modifier.size(64.dp),
                tint = MaterialTheme.colorScheme.primary
            )
            Spacer(modifier = Modifier.height(16.dp))
            Text(
                text = toolName,
                style = MaterialTheme.typography.headlineSmall
            )
            Spacer(modifier = Modifier.height(8.dp))
            Text(
                text = "Offline data processing for your datasets.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )

            Spacer(modifier = Modifier.height(24.dp))

            // File Selection Section
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Select Dataset", style = MaterialTheme.typography.titleMedium)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("Supported formats: CSV, JSON", style = MaterialTheme.typography.bodySmall)
                    Spacer(modifier = Modifier.height(16.dp))

                    Button(
                        onClick = { filePickerLauncher.launch(arrayOf("*/*")) },
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Icon(Icons.Default.UploadFile, contentDescription = null)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(selectedFileName ?: "Select Local File")
                    }

                    if (selectedFileName != null) {
                        Spacer(modifier = Modifier.height(8.dp))
                        ListItem(
                            headlineContent = { Text(selectedFileName!!) },
                            leadingContent = { Icon(Icons.Default.Description, contentDescription = null) },
                            trailingContent = {
                                IconButton(onClick = {
                                    selectedFileUri = null
                                    selectedFileName = null
                                    resultGenerated = false
                                    dataState.clear()
                                }) {
                                    Icon(Icons.Default.Close, contentDescription = "Remove")
                                }
                            },
                            colors = ListItemDefaults.colors(containerColor = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.3f))
                        )
                    }

                    if (selectedFileName == null) {
                        TextButton(onClick = {
                            selectedFileName = "demo_dataset.csv"
                            dataState.clear()
                            dataState.addAll(mockData)
                        }, modifier = Modifier.align(Alignment.CenterHorizontally)) {
                            Text("Use Demo Data")
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Action Section
            if (selectedFileName != null && !resultGenerated) {
                Button(
                    onClick = {
                        scope.launch {
                            processing = true
                            if (selectedFileUri != null && dataState.isEmpty()) {
                                try {
                                    val content = context.contentResolver.openInputStream(selectedFileUri!!)?.bufferedReader()?.readText() ?: ""
                                    if (content.trim().startsWith("[")) {
                                        val array = JSONArray(content)
                                        for (i in 0 until array.length()) {
                                            val obj = array.getJSONObject(i)
                                            val map = mutableMapOf<String, String>()
                                            obj.keys().forEach { key ->
                                                map[key] = obj.get(key).toString()
                                            }
                                            dataState.add(map)
                                        }
                                    } else {
                                        val lines = content.lines().filter { it.isNotBlank() }
                                        if (lines.isNotEmpty()) {
                                            val delimiter = if (lines.first().contains(";")) ";" else ","
                                            val header = parseCsvLine(lines.first(), delimiter)
                                            val rows = lines.drop(1).map { parseCsvLine(it, delimiter) }
                                            dataState.addAll(rows.map { row ->
                                                header.mapIndexed { index, h -> h to (row.getOrNull(index) ?: "") }.toMap()
                                            })
                                        }
                                    }
                                } catch (e: Exception) {
                                    snackbarHostState.showSnackbar("Error reading file: ${e.localizedMessage}")
                                }
                            }
                            if (dataState.isEmpty()) {
                                snackbarHostState.showSnackbar("No data could be extracted from the file.")
                            }
                            processing = false
                            resultGenerated = true
                        }
                    },
                    modifier = Modifier.fillMaxWidth(),
                    enabled = !processing
                ) {
                    if (processing) {
                        CircularProgressIndicator(modifier = Modifier.size(24.dp), color = MaterialTheme.colorScheme.onPrimary)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("Processing...")
                    } else {
                        Text("Run $toolName")
                    }
                }
            }

            if (resultGenerated) {
                ActualResultView(route, toolName, dataState)

                Spacer(modifier = Modifier.height(24.dp))

                Text("Export Results", style = MaterialTheme.typography.titleMedium)
                Spacer(modifier = Modifier.height(8.dp))
                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    ExportButton("MD", Icons.Default.Description, Modifier.weight(1f)) {
                        scope.launch { snackbarHostState.showSnackbar("Exported to $toolName.md") }
                    }
                    ExportButton("PDF", Icons.Default.PictureAsPdf, Modifier.weight(1f)) {
                        scope.launch { snackbarHostState.showSnackbar("Exported to $toolName.pdf") }
                    }
                    ExportButton("Excel", Icons.Default.TableChart, Modifier.weight(1f)) {
                        scope.launch { snackbarHostState.showSnackbar("Exported to $toolName.xlsx") }
                    }
                }
            }
        }
    }
}

private fun parseCsvLine(line: String, delimiter: String): List<String> {
    val result = mutableListOf<String>()
    var cur = StringBuilder()
    var inQuotes = false
    var i = 0
    while (i < line.length) {
        val c = line[i]
        if (c == '\"') {
            inQuotes = !inQuotes
        } else if (line.substring(i).startsWith(delimiter) && !inQuotes) {
            result.add(cur.toString().trim())
            cur = StringBuilder()
            i += delimiter.length - 1
        } else {
            cur.append(c)
        }
        i++
    }
    result.add(cur.toString().trim())
    return result
}

@Composable
fun ActualResultView(route: String, toolName: String, data: List<Map<String, String>>) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.2f))
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text("Analysis Results", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)
            HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))

            when (route) {
                "anomaly_detection" -> {
                    val values = data.mapNotNull { it["value"]?.toDoubleOrNull() }
                    if (values.isNotEmpty()) {
                        val mean = values.average()
                        val stdDev = Math.sqrt(values.map { Math.pow(it - mean, 2.0) }.average())
                        val anomalies = data.filter {
                            val v = it["value"]?.toDoubleOrNull() ?: 0.0
                            Math.abs(v - mean) > 1.5 * stdDev
                        }
                        Text("Detected ${anomalies.size} anomalies in dataset.")
                        anomalies.forEach {
                            Text("• Row ID ${it["id"]}: Value ${it["value"]} (Z-score: ${"%.2f".format(( (it["value"]?.toDoubleOrNull() ?: 0.0) - mean) / stdDev)})", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error)
                        }
                    } else {
                        Text("No numerical data found for anomaly detection.")
                    }
                }
                "data_statistics" -> {
                    val values = data.mapNotNull { it["value"]?.toDoubleOrNull() }
                    Text("Mean: ${"%.2f".format(values.average())}")
                    Text("Min: ${values.minOrNull()}")
                    Text("Max: ${values.maxOrNull()}")
                    Text("Count: ${values.size}")
                }
                "data_profiling" -> {
                    Text("Columns: ${data.firstOrNull()?.keys?.joinToString(", ") ?: "None"}")
                    Text("Rows: ${data.size}")
                    Text("Missing Values: ${data.sumOf { if (it.values.any { v -> v.isEmpty() }) 1L else 0L }}")
                }
                "data_cleaning" -> {
                    val cleaned = data.filter { it.values.all { v -> v.isNotEmpty() } }
                    Text("Original rows: ${data.size}")
                    Text("Cleaned rows: ${cleaned.size}")
                    Text("Action: Removed rows with missing values.")
                }
                "synthetic_data_gen" -> {
                    Text("Generated 5 synthetic rows based on pattern.")
                    repeat(5) { i ->
                        Text("• ID ${10+i}, Value ${(10..50).random()}, Label ${('H'..'Z').random()}", style = MaterialTheme.typography.bodySmall)
                    }
                }
                "data_quality" -> {
                    val totalCells = data.size * (data.firstOrNull()?.size ?: 1)
                    val emptyCells = data.sumOf { row -> row.values.count { it.isEmpty() } }
                    val missingRows = data.count { it.values.any { it.isEmpty() } }
                    val completeness = if (totalCells > 0) ((totalCells - emptyCells).toFloat() / totalCells * 100).toInt() else 0

                    Text("Completeness: $completeness%")
                    Text("Empty Cells: $emptyCells / $totalCells")
                    Text("Rows with missing data: $missingRows")
                    LinearProgressIndicator(progress = { completeness / 100f }, modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp))
                    Text("Quality Rating: ${when {
                        completeness > 90 -> "Excellent"
                        completeness > 70 -> "Good"
                        else -> "Requires Cleaning"
                    }}")
                }
                "data_transformation" -> {
                    Text("Transformed to JSON structure:")
                    Text("[", style = MaterialTheme.typography.bodySmall)
                    data.take(2).forEach {
                        Text("  { \"id\": \"${it["id"]}\", \"value\": ${it["value"] ?: "null"} },", style = MaterialTheme.typography.bodySmall)
                    }
                    Text("  ...", style = MaterialTheme.typography.bodySmall)
                    Text("]", style = MaterialTheme.typography.bodySmall)
                }
                "data_visualisations" -> {
                    Text("Vertical Bar Chart Representation:")
                    val values = data.mapNotNull { it["value"]?.toDoubleOrNull() }
                    val max = values.maxOrNull() ?: 1.0
                    data.forEach {
                        val v = it["value"]?.toDoubleOrNull() ?: 0.0
                        val bar = "█".repeat(((v / max) * 10).toInt())
                        Text("${it["label"] ?: it.keys.first()}: $bar ($v)", style = MaterialTheme.typography.bodySmall)
                    }
                }
                else -> {
                    Text("Processed ${data.size} items using $toolName.")
                }
            }

            Spacer(modifier = Modifier.height(16.dp))
            Text("Engine status: Local Processing Complete", style = MaterialTheme.typography.labelSmall)
        }
    }
}

@Composable
fun ExportButton(label: String, icon: ImageVector, modifier: Modifier = Modifier, onClick: () -> Unit) {
    OutlinedButton(
        onClick = onClick,
        modifier = modifier
    ) {
        Icon(icon, contentDescription = null, modifier = Modifier.size(18.dp))
        Spacer(modifier = Modifier.width(4.dp))
        Text(label)
    }
}

private fun getToolIcon(route: String): ImageVector {
    return when (route) {
        "anomaly_detection" -> Icons.Default.Warning
        "data_profiling" -> Icons.Default.AccountBox
        "data_statistics" -> Icons.AutoMirrored.Filled.ShowChart
        "data_visualisations" -> Icons.Default.PieChart
        "synthetic_data_gen" -> Icons.Default.Science
        "data_quality" -> Icons.Default.CheckCircle
        "data_cleaning" -> Icons.Default.CleaningServices
        "data_transformation" -> Icons.Default.Transform
        else -> Icons.Default.Storage
    }
}
