# Generated by Django 3.2.12 on 2022-03-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge_api', '0002_alter_report_execution_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='123', max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=100)),
                ('credentials', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DQDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dataset', models.CharField(max_length=100)),
                ('ref_datasets', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json', models.TextField()),
                ('example', models.TextField()),
                ('default_threshold', models.FloatField(default=1)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dq_dimension_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.dqdimension')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json', models.TextField()),
                ('threshold', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cde_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.cde')),
                ('rule_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.rulemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.IntegerField(default=0)),
                ('records_passed', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('p_records_passed', models.FloatField(default=0)),
                ('p_records_failed', models.FloatField(default=0)),
                ('result_status', models.BooleanField()),
                ('json_result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.project')),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.rule')),
            ],
        ),
        migrations.CreateModel(
            name='DataProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=100)),
                ('ref_datasets', models.TextField()),
                ('fields', models.TextField()),
                ('total_records', models.IntegerField()),
                ('report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.datasource')),
            ],
        ),
        migrations.AddField(
            model_name='cde',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge_api.project'),
        ),
    ]
