# Generated by Django 4.1 on 2022-09-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dag_id', models.CharField(max_length=200, unique=True)),
                ('run_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('source_env', models.CharField(default='airflow', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('run_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('execution_date', models.DateTimeField()),
                ('state', models.CharField(max_length=20)),
                ('parent_child_map', models.TextField()),
                ('upstreams_map', models.TextField()),
                ('pipeline_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_run', to='dbnd_server.pipelinedefinition')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('task_definition_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('source', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('task_run_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('is_root', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=20)),
                ('task_run_params', models.TextField()),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_run', to='dbnd_server.pipelinerun')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_run', to='dbnd_server.taskdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRunAttempt',
            fields=[
                ('task_run_attempt_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=20)),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_run_attempt', to='dbnd_server.taskrun')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRunMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('metric', models.TextField()),
                ('task_run_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_run_metric', to='dbnd_server.taskrunattempt')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRunLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_body', models.TextField()),
                ('local_log_path', models.TextField()),
                ('task_run_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_run_log', to='dbnd_server.taskrunattempt')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=20)),
                ('operation_status', models.CharField(max_length=20)),
                ('operation_error', models.TextField()),
                ('task_run_name', models.CharField(max_length=200)),
                ('value_preview', models.TextField()),
                ('with_partition', models.CharField(max_length=200)),
                ('data_dimensions', models.TextField()),
                ('data_schema', models.TextField()),
                ('query', models.TextField()),
                ('dataset_uri', models.CharField(max_length=200)),
                ('columns_stats', models.TextField()),
                ('operation_path', models.CharField(max_length=100)),
                ('operation_source', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_log', to='dbnd_server.pipelinerun')),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_log', to='dbnd_server.taskrun')),
                ('task_run_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_log', to='dbnd_server.taskrunattempt')),
            ],
        ),
    ]
