# Generated by Django 4.1 on 2022-09-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbnd_server', '0002_alter_datasetlog_operation_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrunmetric',
            name='source',
            field=models.TextField(),
        ),
    ]
