# Generated by Django 4.1 on 2022-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbnd_server', '0004_alter_datasetlog_value_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetlog',
            name='columns_stats',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datasetlog',
            name='with_partition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
