# Generated by Django 4.1 on 2022-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbnd_server', '0009_taskrun_end_date_taskrun_execution_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrunmetric',
            name='metric',
        ),
        migrations.AddField(
            model_name='taskrunmetric',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskrunmetric',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskrunmetric',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskrunmetric',
            name='value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taskrunmetric',
            name='value_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='taskrunmetric',
            name='value_json',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskrunmetric',
            name='value_str',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskrunmetric',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
