[config]
# add more rule in field_mask with comma (,) separated
field_mask = IPADDRESS

# Database setting to fetch service principal credentials
server_name = tcp:prathamcdpserver.database.windows.net,1433
database_name = cdp_db
user_name = cdpadmin
password = device@123

# zone declaration
raw_data_zone = raw
curated_data_zone = curated

# Subscription where service principal and zones are created
subscription_id = cdd13030-77e0-41a5-b0d9-558c7e10551c