# Generated by Django 4.0.4 on 2022-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=40)),
                ('default_config', models.JSONField()),
                ('configured_value', models.JSONField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_yml', models.TextField(default='global:\nscrape_interval: 15s\nscrape_timeout: 10s\nevaluation_interval: 1m\n\nremote_write:\n- url: "http://influxdb:8086/api/v1/prom/write?u=admin&p=admin&db=prometheus"\nremote_read:\n- url: "http://influxdb:8086/api/v1/prom/read?u=admin&p=admin&db=prometheus"\n\nscrape_configs:\n- job_name: "prometheus"\n  static_configs:\n    - targets: ["prometheus:9090"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
