# Generated by Django 4.0.4 on 2022-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigString',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=40, null=True)),
                ('value', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
