name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew :app:assembleDebug

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk nature-tools-debug.apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nature-tools-debug
        path: nature-tools-debug.apk

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Download APK
      uses: actions/download-artifact@v4
      with:
        name: nature-tools-debug

    - name: Get Version
      id: get_version
      run: |
        MAJOR=$(grep 'major=' version.properties | cut -d'=' -f2)
        MINOR=$(grep 'minor=' version.properties | cut -d'=' -f2)
        PATCH=$(grep 'patch=' version.properties | cut -d'=' -f2)
        BUILD=$(grep 'build=' version.properties | cut -d'=' -f2)
        echo "VERSION=$MAJOR.$MINOR.$PATCH-$BUILD" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: Release v${{ steps.get_version.outputs.VERSION }}
        files: nature-tools-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
