name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew :app:assembleDebug

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk nature-tools-debug.apk

    - name: Get Version
      id: get_version
      run: |
        MAJOR=$(grep 'major=' version.properties | cut -d'=' -f2)
        MINOR=$(grep 'minor=' version.properties | cut -d'=' -f2)
        PATCH=$(grep 'patch=' version.properties | cut -d'=' -f2)
        BUILD=$(grep 'build=' version.properties | cut -d'=' -f2)
        RUN_NUMBER=${{ github.run_number }}

        if [ "${{ github.event_name }}" == "pull_request" ]; then
          PR_NUMBER=${{ github.event.pull_request.number }}
          VERSION="$MAJOR.$MINOR.$PATCH-PR$PR_NUMBER-$RUN_NUMBER"
        else
          VERSION="$MAJOR.$MINOR.$PATCH-$BUILD-$RUN_NUMBER"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: Release v${{ steps.get_version.outputs.VERSION }}
        files: nature-tools-v${{ steps.get_version.outputs.VERSION }}.apk
        prerelease: false
        make_latest: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
